### ISSUE TITLE
[Chore]: Configure a linter and run it in CI

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/cf-k8s-controllers#144]
# Background
We should have a linter configured for all our repositories. We've been using [golangci-lint](https://github.com/golangci/golangci-lint) in eirini for a while now and although not perfect is a good option, as it incorporates many different linters. We can steal the configuration from [here]()

# Actions to take
* add a configuration for golangci-lint in this repository and cf-k8s-controllers
* add a target in the Makefile
* run the linter in CI

# Impact
It'll help us identify and remove problems in our codebase.

**Comment by gcapizzi** [comment]
Work in progress in the [`wip-lints` branch](https://github.com/cloudfoundry/cf-k8s-controllers/tree/wip-lints).
