### ISSUE TITLE
[Feature]: CLI user can run `cf create-space` successfully

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#147]
### Blockers/Dependencies

* cloudfoundry/cf-k8s-api#61
* cloudfoundry/cf-k8s-controllers#166
* cloudfoundry/cf-k8s-controllers#160

### Background

**As a** developer
**I want** to create a space using the `cf` CLI
**And** automatically become a `SpaceManager` and `SpaceDeveloper` for the new space
**So that** I can manage apps in my space

### Acceptance Criteria

**GIVEN** a `cf-k8s-api` instance exists
**AND** an organization exists
**AND** I have targeted the org with `cf target -o <org-name>`
**WHEN I** run `cf create-space <space-name>`
**AND** `cf spaces`
**THEN I** see the created space in the list

**GIVEN** a `cf-k8s-api` instance exists
**AND** an organization exists
**WHEN I** run `cf create-space -o <org-name> <space-name>`
**AND** `cf target -o <org-name>`
**AND** `cf spaces`
**THEN I** see the created space in the list

### Dev Notes

* The CLI will try to assign the [`OrgUser`](https://github.com/eirini-forks/cli/blob/93284695ec2b2d4cdc44d3601986401c342de73c/actor/v7action/role.go#L47), [`SpaceManager`](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/v7/create_space_command.go#L104) and [`SpaceDeveloper`](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/v7/create_space_command.go#L117) roles to the user creating the space. This will in turn need a valid username returned by the `CurrentUser()` method in `Config`. This in turn will need a `/whoami` enpoint. We have discussed these things [here](https://github.com/cloudfoundry/cf-crd-explorations/issues/72#issuecomment-905614411) and [here](https://github.com/cloudfoundry/cf-crd-explorations/issues/71#issuecomment-905534136).

**Comment by kieron-dev** [comment]
See commit above https://github.com/eirini-forks/cli/commit/190558df25c702fee15619542c18d3b77df51f13. This has passing tests.

I've changed the `cmd.Config.CurrentUser()` call to `cmd.Actor.GetCurrentUser()` in the v7 create_space_command, to get the self-contained integration test passing. It remains to change all ~150 invocations of Config.CurrentUser() to the actor variant in the other commands. This will mainly have the effect of showing the current k8s username in the output of the command.

It also remains to build the /whoami endpoint in the API.

**Comment by kieron-dev** [comment]
PR in the CLI repo here: https://github.com/eirini-forks/cli/pull/9
