### ISSUE TITLE
[Feature]: API Client can filter apps by space

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#159]
### Background

**As a** client of the CF API Shim
**I want** to filter apps by space
**So that** I can see the list of apps in the current space

### Acceptance Criteria

**GIVEN** the spaces `space1`, `space2` and `space3` exist
**AND** the apps `app1` and `app2` exist in `space1`
**AND** the apps `app3` and `app4` exist in `space2`
**AND** the apps `app5` and `app6` exist in `space3`
**WHEN I** `GET /v3/apps?space_guids=<guid-of-space-1>,<guid-of-space3>`
**THEN I** see that only `app1`, `app2`, `app5` and `app6` are part of the response

**Comment by tcdowney** [comment]
Work completed in https://github.com/cloudfoundry/cf-k8s-controllers/issues/266
