### ISSUE TITLE
[Feature]: Developer should be able to create apps in a space only if they are a `SpaceDeveloper`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#173]
### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

We want to keep this behaviour behind a feature flag for now, to avoid having a mix of authenticated and unauthenticated endpoints exposed.

### Acceptance Criteria

**GIVEN** two spaces `space1` and `space2` exist
**AND** `user` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`
**WHEN I** create an app in `space1` as `user`
**THEN I** see it working

**GIVEN** two spaces `space1` and `space2` exist
**AND** `user` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`
**WHEN I** try to create an app in `space2` as `user`
**THEN I** get the following response:
```
HTTP/1.1 403 Forbidden
Content-Type: application/json
```
```json
{
  "errors": [
    {
      "code": 10003,
      "title": "CF-NotAuthorized",
      "detail": "You are not authorized to perform the requested action"
    }
  ]
}
```

**Comment by kieron-dev** [comment]
Tracing a `cf push` to see what needs enabling (where cf cli sends auth header):

- [ ] GET /v3/apps/d21faf9e-7447-4cd0-831a-79c8e4049b3a/droplets/current
- [ ] GET /v3/apps/d21faf9e-7447-4cd0-831a-79c8e4049b3a/processes
- [ ] GET /v3/apps/d21faf9e-7447-4cd0-831a-79c8e4049b3a/routes
- [ ] GET /v3/apps?names=foo&space_guids=0e364e44-eac1-431f-9871-2608d7b51a07
- [ ] GET /v3/builds/13d1a114-4b84-4089-bc69-915e56e7eb44
- [ ] GET /v3/droplets/13d1a114-4b84-4089-bc69-915e56e7eb44
- [ ] GET /v3/jobs/sync-space.apply_manifest-0e364e44-eac1-431f-9871-2608d7b51a07
- [ ] GET /v3/processes/7f42b21f-246e-49d3-8d33-20a2b9e3a5a6
- [ ] GET /v3/processes/7f42b21f-246e-49d3-8d33-20a2b9e3a5a6/sidecars
- [ ] GET /v3/processes/7f42b21f-246e-49d3-8d33-20a2b9e3a5a6/stats
- [ ] PATCH /v3/apps/d21faf9e-7447-4cd0-831a-79c8e4049b3a/relationships/current_droplet
- [ ] POST /v3/apps/d21faf9e-7447-4cd0-831a-79c8e4049b3a/actions/restart
- [ ] POST /v3/builds
- [ ] POST /v3/packages
- [ ] POST /v3/packages/0829a139-fb17-4f69-8dc6-2bbd3c9650fc/upload
- [ ] POST /v3/resource_matches
- [ ] POST /v3/spaces/0e364e44-eac1-431f-9871-2608d7b51a07/actions/apply_manifest

Will need to authorize the resources and test all these endpoints.

**Comment by tcdowney** [comment]
> Will need to authorize the resources and test all these endpoints. Interestingly, POST to /v3/apps isn't included, which is what we assumed cf push would do.

It used to. 😅 

These days the bulk of app creation / configuration work is handled by the `POST /v3/spaces/[space-guid]/actions/apply_manifest` endpoint. The CLI converts most actions/flags into a manifest yaml that they merge on to any user-provided app manifest.
