### ISSUE TITLE
[Feature]: API Client cannot create a duplicate route

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-k8s-controllers#178]
### Background

As a client of the API shim
I want to receive an error when I attempt to create a duplicate route based on its FQDN + context path
So that I am prevented from creating a route if it already exists

#### With context path
**GIVEN** I have an existing route (e.g. `foo.example.com/bar` )
**WHEN** I try to make another route with that same host, domain, and context path
**THEN** receive a `422` error

```json
{
  "errors": [
    {
      "code": 10008,
      "detail": "Route already exists with host 'foo' and path '/bar' for domain 'atom-kitten.capi.land'.",
      "title": "CF-UnprocessableEntity"
    }
  ]
}
```

#### Without context path
**GIVEN** I have an existing route (e.g. `foo.example.com` )
**WHEN** I try to make another route with that same host and domain
**THEN** receive a `422` error

```json
{
  "errors": [
    {
      "code": 10008,
      "detail": "Route already exists with host 'foo' for domain 'atom-kitten.capi.land'.",
      "title": "CF-UnprocessableEntity"
    }
  ]
}
```

### Dev Notes

* Start by implementing this the same way as we do for app names (with leases)
  * We recognize that the direct kubectl apply use case may not have sufficient guards against tampering, but the main API use case remains covered

**Comment by tcdowney** [comment]
Output from a CF for VMs env when creating a duplicate route:
```json
REQUEST: [2022-02-14T10:33:04-07:00]
POST /v3/routes HTTP/1.1
Host: api.atom-kitten.capi.land
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/8.1.0+034d929d7.2022-01-03 (go1.16.6; amd64 darwin)
{
  "host": "foo",
  "relationships": {
    "domain": {
      "data": {
        "guid": "44085066-fdb5-452f-92aa-6d7b2a7c0766"
      }
    },
    "space": {
      "data": {
        "guid": "ed61c32e-1aa8-4817-a5dd-6059ae40a32b"
      }
    }
  }
}


RESPONSE: [2022-02-14T10:33:04-07:00]
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json; charset=utf-8
Date: Mon, 14 Feb 2022 17:33:04 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-B3-Spanid: 2fb9367e253e653207c4f98d4c72e3a9
X-B3-Traceid: 2fb9367e253e653207c4f98d4c72e3a9
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.029722
X-Vcap-Request-Id: ec1e2672-a2d2-4807-6a7d-d309378f9149::850375bf-ad8d-4ba1-b595-1fa8164f437e
X-Xss-Protection: 1; mode=block
{
  "errors": [
    {
      "code": 10008,
      "detail": "Route already exists with host 'foo' for domain 'atom-kitten.capi.land'.",
      "title": "CF-UnprocessableEntity"
    }
  ]
}
```

**Comment by tcdowney** [comment]
Food for thought: Unlike most resources, Domains in CF can't be updated. I know the CRs can right now, but if we found ways to make them "immutable-ish" that could help with those questions.

https://v3-apidocs.cloudfoundry.org/version/3.115.0/index.html#update-a-domain

**Comment by kieron-dev** [comment]
It also seems impossible to update host, path and domain on a route via the API. So maybe they should be made immutable too.
