### ISSUE TITLE
[Feature]: API Client can add a destination to a route

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/cf-k8s-controllers#184]
### Blockers/Dependencies

Blocked by cloudfoundry/cf-k8s-api#38.

### Background

**As a** client of the CF API
**I want** to add a destination to a CFRoute resource
**So that** that I can route traffic to apps on CF on Kubernetes

The behavior of this endpoint should match the existing behavior of the POST `/v3/routes/[guid]/destinations` endpoint in CF for VMs as closely as possible -- including the error cases. Limit the scope of response data to exclude a distinct destination GUID for now, we would like to defer the decision of destination representation. For basic cases, copying the app guid should suffice, especially given the initial focus on single-process apps

### Acceptance Criteria

GIVEN I have the API shim running locally according to the README
AND I have created the sample `cfdomain.yaml`, `cfroute.yaml`, and `cfapp.yaml` resources from [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers) on my target kubernetes cluster.
THEN I can perform the following scenarios

### Happy Path

**WHEN** I make the following request
```
curl "https://api.example.org/v3/routes/84afc0f2-3dc2-4709-9fc8-8340be584a43/destinations" \
  -X POST \
  -H "Authorization: bearer [token]"
  -H "Content-type: application/json"
  -d '{
    "destinations": [
      {
        "app": {
          "guid": "14dcda7d-1fa1-4a91-b437-fbdba20e8c5a"
        }
      }
    ]
  }'
```

**THEN** I get the following response
```
HTTP/1.1 200 OK
Content-Type: application/json

  {
    "destinations": [
      {
        "guid": "14dcda7d-1fa1-4a91-b437-fbdba20e8c5a",
        "app": {
          "guid": "14dcda7d-1fa1-4a91-b437-fbdba20e8c5a",
          "process": {
            "type": "web"
          }
        },
        "weight": null,
        "port": 8080,
        "protocol": "http2"
      },
    ],
    "links": {
      "self": {
        "href": "https://api.example.org/v3/routes/84afc0f2-3dc2-4709-9fc8-8340be584a43/destinations"
      },
      "route": {
        "href": "https://api.example.org/v3/routes/84afc0f2-3dc2-4709-9fc8-8340be584a43"
      }
    }
  }
```

### Request is invalid (invalid request body)
WHEN I make the following request
```
curl "https://api.example.org/v3/routes/[guid]/destinations" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d 'bad json'
```

THEN The CFRoute CR is not updated
AND I get back the following response
```
HTTP/1.1 400 Bad Request

{
  "errors": [
    {
      "detail": "Request invalid due to parse error: invalid request body",
      "title": "CF-MessageParseError",
      "code": 1001
    }
  ]
}
```
### Request is invalid (route does not exist)
**WHEN** I make the following request
```
curl "https://api.example.org/v3/routes/not-a-route-guid/destinations" \
  -X POST \
  -H "Authorization: bearer [token]"
  -H "Content-type: application/json"
  -d '{
    "destinations": [
      {
        "app": {
          "guid": "not-an-app-guid"
        }
      }
    ]
  }'
```

**THEN** the CFRoute is not updated
**AND** I receive the following response
```
HTTP/1.1 404 Not Found

{
  "errors": [
    {
      "detail": "Route not found",
      "title": "CF-ResourceNotFound",
      "code": 10010
    }
  ]
}
```

### Request is invalid (app does not exist )
**WHEN** I make the following request
```
curl "https://api.example.org/v3/routes/84afc0f2-3dc2-4709-9fc8-8340be584a43/destinations" \
  -X POST \
  -H "Authorization: bearer [token]"
  -H "Content-type: application/json"
  -d '{
    "destinations": [
      {
        "app": {
          "guid": "not-an-app-guid"
        }
      }
    ]
  }'
```

**THEN** the CFRoute is not updated
**AND** I receive the following response
```
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "App(s) with guid(s) \"not-an-app-guid\" do not exist or you do not have access.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

### Request is invalid (app does not exist in the same space as the route)
**WHEN** I make the following request
```
curl "https://api.example.org/v3/routes/84afc0f2-3dc2-4709-9fc8-8340be584a43/destinations" \
  -X POST \
  -H "Authorization: bearer [token]"
  -H "Content-type: application/json"
  -d '{
    "destinations": [
      {
        "app": {
          "guid": "different-space-app-guid"
        }
      }
    ]
  }'
```

**THEN** the CFRoute is not updated
**AND** I receive the following response
```
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "App(s) with guid(s) \"different-space-app-guid\" do not exist or you do not have access.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

**Comment by tcdowney** [comment]
@acosta11 ,`cf map-route` works now so can this issue be closed? Or was there still more to be done?

**Comment by acosta11** [comment]
Indeed, this was just the base add destination functionality which is done. Closing.
