### ISSUE TITLE
[Explore]: Packaging source code as Carvel's imgpkg

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/cf-k8s-controllers#187]
### Background

In the CF API Spike implementation, the uploaded source code is converted into a Single Layer OCI image. One of the feedback comment received on this [approach](https://miro.com/app/board/o9J_lFiI8CU=/?moveToWidget=3074457362429500346&cot=14) is to convert the uploaded source code zip into [Carvel's `imgpkg`](https://carvel.dev/imgpkg/) instead of a single layer OCI image. 

**CF for VMs context**
During cf push the CLI will package up the local app source code into a zip file (referred to as app bits) and send it to the Cloud Controller API. The Cloud Controller API will do some additional processing (a big portion of this is a feature called resource matching) and send the app `bits` to the packages bucket in the `blobstore`. The associated CF Package for these bits will be updated to have the state `READY` to indicate that the source code has been fully uploaded.

**CF for K8s context**
In CF for K8s we use [`kpack`](https://github.com/pivotal/kpack) for application staging and provide the app source code as an OCI image. In this flow the CLI will still package the local app source code as a zip file and sent it to the Cloud Controller API. Instead of sending it to a blobstore, though, Cloud Controller will pass the zip off to another component called [`registry-buddy`](https://github.com/cloudfoundry/capi-k8s-release/tree/main/src/registry-buddy) which [converts the zip file into a single-layer OCI image](https://github.com/cloudfoundry/capi-k8s-release/blob/main/src/registry-buddy/package_upload/package_upload.go) that contains the app source. It then pushes that image to an image registry. Once this is done the associated CF Package is updated to have the state `READY` and Cloud Controller implicitly knows where the image was pushed to based on the configured image registry / package guid.

Some of the questions we would like to answer through this explore is to

- **Feasibility** - We plan on using kpack for application staging in CF on K8s. Will moving to a `imgpkg` format break the feasibility of staging with kpack?

- **Complexity** - Do we take up additional complexity to convert the source code to a `imgpkg` and to stage with `kpack`. How will re-staging work when there are stack updates? 

- **Benefits** - Do we see benefits of using `imgpkg` be of value to CF users. 

- Are there any downsides?

### Acceptance Criteria

By the end of this explore we should have a ADR of packaging tool - use of carvels`imgpkg` as compared to use of single layer OCI image.

### Number of days this exploration is expected to take. This is what is “pointed”.

Time box: 2 days

**Comment by tcdowney** [comment]
Closing: This exploration was completed and the decision was documented in [this ADR](https://github.com/cloudfoundry/cf-k8s-controllers/blob/203306701a4825584a514138bcd8cf73c877d7e4/api/docs/architecture-decisions/0003-cf-package-source-image-format.md). We decided not to use the `imgpkg` format for our app source images.
