### ISSUE TITLE
[Chore]: Consolidate README for cf-k8s-controllers and cf-k8s-api to top level

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/cf-k8s-controllers#192]
### Background

The [cf-k8s-api](https://github.com/cloudfoundry/cf-k8s-api) repo has been merged into [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers). There are two separate README files that should be top level in a single document.

### Action to take

Merge the two READMEs into a single top level README

### Impact

This is a high visibility item for anyone visiting the repository.

**Comment by georgethebeatle** [comment]
Hey @Birdrock, it looks like the README files has already been merged. Are there more improvements that you have in mind or should we close this chore?

**Comment by georgethebeatle** [comment]
Closing this as stale. Please reopen if there is more stuff to be done here.
