### ISSUE TITLE
[Feature]: Platform Operator can see instructions to manually install HNC in the README

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-k8s-controllers#213]
### Background

**As a** platform operator
**I want** instructions to manually install HNC
**So that** I can install all of the dependencies for cf-k8s-controllers

### Acceptance Criteria

**GIVEN** that I am trying to install the cf-k8s-controllers
**WHEN I** follow the instructions in the README
**THEN I** can install HNC on my cluster

**Comment by julian-hj** [comment]
We also noticed that the HNC version in the `install-dependencies` script is out of date and points to the older repo.

The new one:
https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v0.9.0/hnc-manager.yaml

Also we should replace all the references to the `hack/` folder to say `scripts/` instead.
