### ISSUE TITLE
[Feature]: End user can configure controllers

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/cf-k8s-controllers#24]
### Blockers/Dependencies

Blocked by #23 

**Blocked by a forthcoming RFC regardless choices of templating mechanism and tools.**
Require input from:
* European time zones
* SAP

### Background

As a end user
I want configuration options
So that modify the controller configuration

### Acceptance Criteria

GIVEN a deployable controller set
WHEN I modify the configuration interface
THEN I see my changes reflected in on the running controller pod

* Update README with conventions for configuration (defaults, structure, etc)

### Dev Notes

This may be a combination of configuration options.
* The image should be configurable, through some templating or patching solution (i.e.: kustomize, ytt, etc).
* Any configuration that can be added by ConfigMaps and Secrets should be done that way, even if those are templated, as well.

**Comment by tcdowney** [comment]
Closing: We've got kustomize templates and config files now for the controllers. Future changes can have their own, more targeted stories.
