### ISSUE TITLE
[Feature]: App developer can restart an application w/ downtime (Controller implementation)

### ISSUE THREAD

**Issue by gnovv** [cloudfoundry/cf-k8s-controllers#260]
### Blockers/Dependencies

Follow up to https://github.com/cloudfoundry/cf-k8s-controllers/issues/170

### Background

As an App developer
I want to be able to issue a restart command
So that restart my workload

Previously we implemented V3 restart app using the api shim and watching the app's pods in order to synchronously set the app's desiredState to started.

Now we want to implement this functionality on the Controller side so that it is asynchronous and more robust.

### Acceptance Criteria

**GIVEN** my app exists
**WHEN I** issue a start command
```
curl "https://api.example.org/v3/apps/<guid>/actions/restart" \
  -X POST \
  -H "Authorization: bearer <token>"
```

**THEN I** get a response similar to the following
```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "guid": "1cb006ee-fb05-47e1-b541-c34179ddc446",
  "name": "my_app",
  "state": "STARTED",
  "created_at": "2016-03-17T21:41:30Z",
  "updated_at": "2016-03-18T11:32:30Z",
  "lifecycle": {
    "type": "buildpack",
    "data": {
      "buildpacks": ["java_buildpack"],
      "stack": "cflinuxfs3"
    }
  },
  "relationships": {
    "space": {
      "data": {
        "guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446"
    },
    "space": {
      "href": "https://api.example.org/v3/spaces/2f35885d-0c9d-4423-83ad-fd05066f8576"
    },
    "processes": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/processes"
    },
    "packages": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/packages"
    },
    "environment_variables": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/environment_variables"
    },
    "current_droplet": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/droplets/current"
    },
    "droplets": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/droplets"
    },
    "tasks": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/tasks"
    },
    "start": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/actions/start",
      "method": "POST"
    },
    "stop": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/actions/stop",
      "method": "POST"
    },
    "revisions": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/revisions"
    },
    "deployed_revisions": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/revisions/deployed"
    },
    "features": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/features"
    }
  },
  "metadata": {
    "labels": {},
    "annotations": {}
  }
}
```

**AND WHEN I** issue a kubectl describe on my underlying app workload
```
kubectl get pods -n <space-guid> <TODO: filter-by-flag> workloads.cloudfoundry.org/app-guid=<the-app-guid>
```

**THEN I** get different pods back(same name, but age will be younger)

### Dev Notes

- We have a Miro board capturing some background details and possible implementation leads: https://miro.com/app/board/o9J_l0Jgo7k=/
- if the approach taken by the pair working on this is not obvious, think about writing an ADR to capture your decisions.
- Update the cf-k8s-api to use the new controllers implementation
  - end point can be asynchronous
  - presenter needs to be updated

**Comment by gnovv** [comment]
TODO:

- [ ] Make a cool diagram

- [ ] Webhook for adding rev annotation to CFApp
  - [ ] Integration Test
  - [ ] Implementation

- [ ] CFProcess Controller
  - [ ] handle patching/lookup via labels
    - [ ] Integration Test
    - [ ] Implementation
  - [ ] create LRPs based on rev(hash) + ProcessGUID
    - [ ] Integration Test
    - [ ] Implementation
  - [ ] cleanup old LRPs with former rev
    - [ ] Integration Test
    - [ ] Implementation

-[ ] API Shim
  - [ ] Update actions/stop to bump rev on CFApp
    - [ ] Integration Test
    - [ ] Implementation
  - [ ] Find and fix any former endpoints that rely on old LRP naming schema

**Comment by gnovv** [comment]
We learned that `cf restart` doesn't actually use the `actions/restart` endpoint so we revised our implementation plan to focus on the CFProcess Controller

**Comment by tcdowney** [comment]
@akrishna90 what is the behavior here? Does the stats endpoint incorrectly report that a terminating Pod is healthy and `RUNNING` so the CLI exits it's polling loop too soon?

**Comment by tcdowney** [comment]
> Also we observed that eirini doesn't propagate labels set on the LRP resources down to the Pods.

If we need this we can use the `version` field on the LRP. I think it's conceptually the same thing as what we're using `rev` for.

* https://github.com/cloudfoundry-incubator/eirini-controller/blob/31dd250190f7fef2e9ee01c7793e68d31c2f08c5/deployment/helm/templates/core/lrp-crd.yml#L138
* https://github.com/cloudfoundry-incubator/eirini-controller/blob/31dd250190f7fef2e9ee01c7793e68d31c2f08c5/k8s/stset/lrp_to_statefulset.go#L168

**Comment by gnovv** [comment]
> @akrishna90 what is the behavior here? Does the stats endpoint incorrectly report that a terminating Pod is healthy and `RUNNING` so the CLI exits it's polling loop too soon?

That's right. Eventually the new pods come up, but cf restart exits too early

**Comment by tcdowney** [comment]
> That's right. Eventually the new pods come up, but cf restart exits too early

I think that's not great because if the new Pods fail to start for any reason the command will have exited successfully and any scripts/people running it will mistakenly think their app is doing fine.

I think we should come up with a plan to make it work better at least.

**Comment by akrishna90** [comment]
@tcdowney  We decided to set the lrp's `version` value to be equal to `app-rev`. We decided to handle updating the `GET /v3/processes/<process-guid>/stats` endpoint in a separate story.
