### ISSUE TITLE
[Chore]: Check if we are vulnearable to ChainJacking

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-k8s-controllers#275]
### Background

There is a vulnerability of golang modules called [chain jacking](https://checkmarx.com/blog/a-new-type-of-supply-chain-attack-could-put-popular-admin-tools-at-risk/). The idea is that if you depend on a go module from github that is hosted from a regular github user (not an org) and the user changes their handle, the old handle becomes available and a malicious user can take it and host a modified version of the code, thus attacking your app.

### Action to take

Let's try the chain jacking [tool](https://github.com/checkmarx/chainjacking) to detect if we have any depencencies that are vulnerable to this attack. We should also consider adding a github action that checks that when a PR comes in (there is an example for that in the chain jacking repo.

### Impact

We are not vulnerable to chain jacking

**Comment by gcapizzi** [comment]
```
~/workspace/cf-k8s-controllers main
❯ python3 -m chainjacking -gt "..."
✅ Dependencies analyzed and found to be safe from ChainJacking attacks
```
