### ISSUE TITLE
[Feature]: API Client can see that Droplet app and build labels are set automatically

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/cf-k8s-controllers#28]
### Blockers/Dependencies

- #25 

### Background

As an API Client
I want the appGUID and buildGUID labels on CFDroplet to be set automatically
So that I can look up CFDroplet records by appGUID and buildGUID

We encode the relationships between resources in two ways: via "ref" fields under `spec` and via `metadata.labels`. Rather than rely on our code and/or kubectl users to always remember both, we want to require the spec field and automatically set the label via a MutatingAdmissionWebhook

### Acceptance Criteria

GIVEN that I am targeting a k8s cluster
AND  that I have followed the README instructions to install the web hook
WHEN I apply the example CFApp, CFPackage, CFBuild and CFDroplet resource from the `config/samples` directory
THEN I should see all operations succeed
WHEN I fetch the yaml for the CFDroplet record from the k8s API
THEN I should see that the appGUID label has been set on the record and that it matches the `spec.appRef.name` field
AND  I should see that the buildGUID label has been set on the record and that it matches the `spec.buildRef.name` field

### Dev Notes

- Remove the labels from the example resources if they are still present, and commit the change.
- This should apply to creation and updates of records

**Comment by tcdowney** [comment]
Closing this since we're planning on merging the Build and Droplet CRs: https://github.com/cloudfoundry/cf-k8s-controllers/issues/52
