### ISSUE TITLE
[Chore]: Remove any generated code from the code coverage report

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-k8s-controllers#304]
### Background

We have a [code coverage report](https://codeclimate.com/github/cloudfoundry/cf-k8s-controllers)! However there are some files that we do not want to be measuring like fakes and generated code for k8s.

### Action to take

Filter out the unwanted files, so that they do not show in the report

### Impact

We have a more realistic coverage report

### Dev Notes

I am not sure how this is done but I can think of two approaches
- Delete lines from the `cover.out` files prior to [aggregating and publishing](https://github.com/cloudfoundry/cf-k8s-controllers/blob/5a6938002aaa88aaf3c57bb7b4a223dca6c267fe/.github/workflows/test-build-push-main.yml#L163-L169) the final report
- Excluding them using code climate [config](https://docs.codeclimate.com/docs/excluding-files-and-folders)

**Comment by danail-branekov** [comment]
We tried introducing a `.codeclimate.yml` file into the repo hoping that it would filter out generated code from the coverage report. Unfortunately, it did not :(

Looking at the publish coverage github action log:

```
Run paambaati/codeclimate-action@v3.0.0
/home/runner/work/cf-k8s-controllers/cf-k8s-controllers/cc-reporter before-build
ℹ️ 'coverageCommand' not set, so skipping building coverage report!
/home/runner/work/cf-k8s-controllers/cf-k8s-controllers/cc-reporter format-coverage /home/runner/work/cf-k8s-controllers/cf-k8s-controllers/api-integration-coverage/api/cover.out -t gocov -o codeclimate.0.json --prefix code.cloudfoundry.org/cf-k8s-controllers
/home/runner/work/cf-k8s-controllers/cf-k8s-controllers/cc-reporter format-coverage /home/runner/work/cf-k8s-controllers/cf-k8s-controllers/api-unit-coverage/api/cover.out -t gocov -o codeclimate.1.json --prefix code.cloudfoundry.org/cf-k8s-controllers
/home/runner/work/cf-k8s-controllers/cf-k8s-controllers/cc-reporter format-coverage /home/runner/work/cf-k8s-controllers/cf-k8s-controllers/controllers-coverage/controllers/cover.out -t gocov -o codeclimate.2.json --prefix code.cloudfoundry.org/cf-k8s-controllers
/home/runner/work/cf-k8s-controllers/cf-k8s-controllers/cc-reporter sum-coverage codeclimate.0.json codeclimate.1.json codeclimate.2.json -p 3 -o coverage.total.json
/home/runner/work/cf-k8s-controllers/cf-k8s-controllers/cc-reporter upload-coverage -i coverage.total.json
```

It seems that the action runs a `cc-reporter` tool (code [here](https://github.com/codeclimate/test-reporter)) that simply formats and aggregate coverage reports (`cover.out` files) without respecting the configuration.yml. 

Therefore we apparently have two options:
* either remove generated code lines from the `cover.out` files prior running the github action, or
* find a way to not include info for generated code in cover.out files

**Comment by mnitchev** [comment]
closed by #311

**Comment by georgethebeatle** [comment]
Reopening this to address some oddities in the reports, where seemingly the wrong lines are highlighted. For example: https://codeclimate.com/github/cloudfoundry/cf-k8s-controllers/api/apis/job_handler.go/source

Here a method that returns an error appears to not have been called, while the block that handles the error seems to have been called, but only the logger.Error line was marked as executed. This is all very strange. Are lines shifted? If yes what step is producing the wrong report?

A way to test this would be to take the all the raw `cover.out` reports, then render them as html using `go cover` and look at the reports to see if there are oddities like the one described.

Then we can remove the lines about generated code as we do in the [github action](https://github.com/cloudfoundry/cf-k8s-controllers/blob/3f660c4515dd8c2382d99058b5a5e207108c9c1b/.github/workflows/test-build-push-main.yml#L75-L76) and see if this breaks the report.

Finally we can check if the code climate reporter is corrupting the report when [merging](https://github.com/cloudfoundry/cf-k8s-controllers/blob/3f660c4515dd8c2382d99058b5a5e207108c9c1b/.github/workflows/test-build-push-main.yml#L172-L178) the raw files.

**Comment by georgethebeatle** [comment]
We found out that the codeclimate test reporter is breaking the report and opened an [issue](https://github.com/codeclimate/test-reporter/issues/479) in the relevant project. Closing again.

**Comment by georgethebeatle** [comment]
We opened a [PR](https://github.com/codeclimate/test-reporter/pull/480) fixing the issue mentioned above. Reopening this chore to track progress there. Once it makes its way into a release we should revert this [commit](https://github.com/cloudfoundry/cf-k8s-controllers/commit/e84f255d11e19b5f2de6d969a14eb16191d0d345)

**Comment by georgethebeatle** [comment]
We just reverted to using the official version of the test reporter. The version v0.10.2 contains our fix.
