### ISSUE TITLE
[Explore]: How should we structure k8s resource labels?

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/cf-k8s-controllers#31]
### Background

For the CRD spike we used labels like `apps.cloudfoundry.org/appGuid` and `apps.cloudfoundry.org/processGuid`. These were copied over from past Eirini work, and we want to reconsider the correct domain and label structure. We also want to ensure that our labels conform with [the kubernetes label recommendations](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

### Acceptance Criteria

Write up an ADR as a PR with a proposed set of labels for the following cases:
- app GUID
- build GUID
- package GUID
- process GUID
- process type

### Number of days this exploration is expected to take. This is what is “pointed”.
Timeboxed to 1 day 

_No response_

**Comment by tcdowney** [comment]
Closing: This was addressed in PR #39 and the ADR for this decision can be found here: https://github.com/cloudfoundry/cf-k8s-controllers/blob/203306701a4825584a514138bcd8cf73c877d7e4/controllers/docs/architecture-decisions/0005-structuring-kubernetes-resource-labels.md
