### ISSUE TITLE
[Feature]: App Developer can view apps in a space using `cf apps`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#313]
### Background

**As an** App Developer
**I want** to be able to use `cf apps` to view the apps in the space I've targeted
**So that** I can use this common CF developer workflow! 😁 

### Acceptance Criteria

---

###  Space Containing Apps
**GIVEN** I have a targeted an org and space that has apps in it with the CF CLI
**WHEN I** run `cf apps`
**THEN I** see output that looks like the following

```
$ cf apps

Getting apps in org org / space space as admin...

name    requested state   processes             routes
dora    started           web:1/1, worker:0/0   dora.coconut-boar.capi.land
dora2   started           web:1/1, worker:0/0   dora2.coconut-boar.capi.land
```

### Space With No Apps
**GIVEN** I have a targeted an org and space that _does not_ have apps in it with the CF CLI
**WHEN I** run `cf apps`
**THEN I** see output that looks like the following

```
$ cf apps

Getting apps in org org / space s2 as admin...

No apps found
```

### Dev Notes

---

In a space with a single app (with two processes), the `cf` CLI is making the following API requests:

```
11:04 $ cf apps -v | grep -i request: -A1
REQUEST: [2021-11-30T11:04:32-07:00]
GET /v3/apps?order_by=name&space_guids=9a550d17-6fdd-463f-b41f-37b5a0ab43c5 HTTP/1.1
--
REQUEST: [2021-11-30T11:04:32-07:00]
GET /v3/processes?app_guids=64bffb13-fa70-4faa-8d0a-1432b6261211 HTTP/1.1
--
REQUEST: [2021-11-30T11:04:32-07:00]
GET /v3/processes/64bffb13-fa70-4faa-8d0a-1432b6261211/stats HTTP/1.1
--
REQUEST: [2021-11-30T11:04:32-07:00]
GET /v3/processes/c7bcfea2-7bc3-4dfb-8600-52ec6c7d72ed/stats HTTP/1.1
--
REQUEST: [2021-11-30T11:04:32-07:00]
GET /v3/routes?app_guids=64bffb13-fa70-4faa-8d0a-1432b6261211 HTTP/1.1
```

The new things that I'm aware of here are:

1. Update the `GET /v3/apps` endpoint to support the `order_by=name` param
2. Create the `GET /v3/processes` endpoint and allow it to be filterable by `app_guids`
3. Update the `GET /v3/routes` endpoint to support the `app_guids` filter (may collide with work on https://github.com/cloudfoundry/cf-k8s-controllers/issues/308)

### How to build a `cf` CLI to test this with
1. Check out https://github.com/cloudfoundry/cli (`master` branch)
2. Run `make build` this will build the CLI and put the binary in the `out` directory
3. Add the new binary to your path: `export PATH=/Users/tdowney/workspace/cli/out:$PATH`

**Comment by julian-hj** [comment]
**Dev notes**: to view API calls from tas4vms:
prerequisite: install the [smith cli](https://github.com/pivotal/smith)
```
smith claim -p us_2_10
export TOOLSMITHS_ENVIRONMENT_NAME=thistle
smith cf-login
cf co o && cf target -o o && cf create-space s && cf target -s s
cd ~/workspace/cf-acceptance-tests/assets/node
cf p node1
cf create-space s2 && cf target -s s2
cf p node2
CF_TRACE=true cf apps
```
Taking that output and grepping for ^GET produces this:

```
GET / HTTP/1.1
GET /v3 HTTP/1.1
GET /login HTTP/1.1
GET /v3/apps?order_by=name&space_guids=24c8f059-dd55-498b-9769-2ab0fe58094f HTTP/1.1
GET /v3/processes?app_guids=4b7879e2-3926-4013-96e5-c22711c36ce4 HTTP/1.1
GET /v3/processes/4b7879e2-3926-4013-96e5-c22711c36ce4/stats HTTP/1.1
GET /v3/routes?app_guids=4b7879e2-3926-4013-96e5-c22711c36ce4 HTTP/1.1
```
