### ISSUE TITLE
[Feature]: App Developer can start and restart their apps

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#315]
### Blockers/Dependencies

---

## Starting an app
**As an** App Developer using the `cf` CLI
**I want** to be able to restart my app using `cf start MY_APP`
**So that** I can start my stopped app

## Restarting an app
**As an** App Developer using the `cf` CLI
**I want** to be able to restart my app using `cf restart MY_APP`
**So that** I can recreate the running Pods for my app

---

### Starting an App
**GIVEN** I have an App deployed in the `STOPPED` state
**WHEN I** call `cf start MY_APP`
**THEN I** see successful CLI output like this

```bash
cf start dora
Starting app dora in org org / space space as admin...

Waiting for app to start...

Instances starting...
Instances starting...
Instances starting...
Instances starting...

name:              dora
requested state:   started
routes:            dora.coconut-boar.capi.land
last uploaded:     Tue 30 Nov 10:58:04 MST 2021
stack:             cflinuxfs3
buildpacks:
	name             version   detect output   buildpack name
	ruby_buildpack   1.8.48    ruby            ruby

type:           web
sidecars:
instances:      1/1
memory usage:   2048M
     state     since                  cpu    memory        disk          details
#0   running   2021-12-01T16:25:56Z   0.3%   40.7M of 2G   89.6M of 1G

type:           worker
sidecars:
instances:      0/0
memory usage:   256M
There are no running instances of this process.
```

---

### Restarting an App
**GIVEN** I have an App deployed in the `STARTED` state
**WHEN I** call `cf restart MY_APP`
**THEN I** see successful CLI output like this

```bash
cf restart dora
Restarting app dora in org org / space space as admin...

Stopping app...

Waiting for app to start...

Instances starting...
Instances starting...
Instances starting...
Instances starting...

name:              dora
requested state:   started
routes:            dora.coconut-boar.capi.land
last uploaded:     Tue 30 Nov 10:58:04 MST 2021
stack:             cflinuxfs3
buildpacks:
	name             version   detect output   buildpack name
	ruby_buildpack   1.8.48    ruby            ruby

type:           web
sidecars:
instances:      1/1
memory usage:   2048M
     state     since                  cpu    memory        disk          details
#0   running   2021-12-01T16:28:44Z   0.3%   37.9M of 2G   89.6M of 1G

type:           worker
sidecars:
instances:      0/0
memory usage:   256M
There are no running instances of this process.
```

---

### Dev Notes

Both of these CLI commands call a very similar set of endpoints. The only ones that I believe we haven't implemented are:

```
REQUEST: [2021-12-01T09:26:55-07:00]
GET /v3/packages?app_guids=64bffb13-fa70-4faa-8d0a-1432b6261211&order_by=-created_at&per_page=1 HTTP/1.1
--
REQUEST: [2021-12-01T09:26:55-07:00]
GET /v3/packages/76e77646-6fe2-4af2-b31c-007048da8e5b/droplets?per_page=1&states=STAGED HTTP/1.1
```

You should validate this story with the CF CLI, though, to make sure we haven't missed any.

* 2 new endpoints, list packages + ordering, list droplets

### How to build a `cf` CLI to test this with
1. Check out https://github.com/cloudfoundry/cli (`master` branch)
2. Run `make build` this will build the CLI and put the binary in the `out` directory
3. Add the new binary to your path: `export PATH=/Users/tdowney/workspace/cli/out:$PATH`

**Comment by gnovv** [comment]
We will default to sorting by `-created_at` and ignore `order_by` for now. We will create a tech-debt story to implement full ordering to be prioritized at a later date.
