### ISSUE TITLE
[Chore]: Make pagination links usable

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/cf-k8s-controllers#324]
### Background

```
$ cf curl /v3/apps | jq .pagination
{
  "total_results": 7,
  "total_pages": 1,
  "first": {
    "href": "https://api.example.org/v3/apps?page=1"
  },
  "last": {
    "href": "https://api.example.org/v3/apps?page=1"
  },
  "next": null,
  "previous": null
}

cf curl /v3/apps?page=1
{"errors":[{"detail":"The query parameter is invalid: Valid parameters are: 'names, space_guids'","title":"CF-BadQueryParameter","code":10005}]}
```

The links we provide in the pagination response don't actually work. This is poor form for a rest API.

### Action to take

We discussed this in standup, and the consensus was to just remove the "page=" querystring argument for apis that don't allow paging.

### Impact

Low--we are not aware of any clients that are broken by this issue.

**Comment by davewalter** [comment]
While working on adding more query params to the `/v3/routes` endpoint, we noticed that we need to include the query params in the first/last pagination links. We decided to simply use the query params from the request to build the desired links. An example of this can be seen in the [route presenter](https://github.com/cloudfoundry/cf-k8s-controllers/blob/2d18382e98aecbae8cce91b30114eb9fc671d73e/api/presenter/route.go#L127). It requires you to pass the request URI into the presenter when handling the response.
