### ISSUE TITLE
[Feature]: Verify all child resources of an App are eventually deleted when the related `CFApp` is deleted

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#336]
### Blockers/Dependencies

Related to https://github.com/cloudfoundry/cf-k8s-controllers/issues/334.

### Background

**As an** App Developer
**I want** all child resources (`CFBuild`, `CFProcess`, env var `Secret`, `CFPackage`, `EiriniLRP`, kpack `Image`, kpack `Build`, `StatefulSet`, etc.) cleaned up upon CFApp deletion
**So that** I don't pollute my cluster when an App is deleted

### Acceptance Criteria

**GIVEN** I have an App running on the cluster with all of the aforementioned child resources
**WHEN I** delete the `CFApp` resource
**THEN I** see that all of the child resources are eventually cleaned up

### Dev Notes

* Make sure we've got some form of test that covers this!
* This story likely consists of ensuring that we've got `OwnerRefs` properly applied to everything so that they're owned by an App or one of its children.
* We could also potentially leverage finalizers on the `CFApp` to delete anything that doesn't cleanly map to the `OwnerRef` model
* We already have a finalizer to remove destinations from CFRoutes.
* We think that the creator of the CR should set the ownerRef:
   * CFBuild: api shim
   * CFProcess: app controller
   * env vars secret: api shim
   * CFPackage: api shim
   * EiriniLRP: process controller
   * kpack image: cfbuild contoller
   * kpack build: kpack should handle this (test manually)
   * StatefulSet: Eirini should handle this (again, test manually)

**Comment by julian-hj** [comment]
Manual test results:
env vars secret: already has owner ref, manual tests show that it works.
kpack image: already has owner ref. to CFBuild. Manually deleting cfbuild cleans it up.
kpack build: already has owner ref. to Image. Manually deleting cfbuild cleans it up.
LRP: has ownerref to CFProcess. deleted correctly when CFProcess is deleted.
StatefulSet: ownerRef to LRP. Deleted when CFProcess is deleted.
CFProcess: ownerRef is **missing** (deleting app leaves it behind)
CFBuild: ownerRef is **missing**
CFPackage: ownerRef is **missing**
