### ISSUE TITLE
[Feature]: Developer can apply a minimal space manifest to push an app with a default route

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/cf-k8s-controllers#358]
### Blockers/Dependencies

#354

TODO: add specific app name DNS validation and default behavior when routes already exist for the app

### Background

**As an** App Developer
**I want** to be able to omit route configuration for my App as a declarative manifest
**So that**I can have routes automatically configured for my App

For this story, we focus on the `default-route` field of the manifest spec.

```
---
version: 1
applications:
  - name: my-app
     ...
     default-route: true
```

### Acceptance Criteria

**Scenarios**

The happy path scenarios will mirror those specified in #354 with the assumption that the generated default route ends up is a valid FQDN for the existing CFDomain.

## Happy Path (Route does not exist)
**GIVEN** I have a cluster with a cfdomain already created for "example.com" and a manifest that specifies `default-route: true`
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    default-route: true
```
**THEN I** I see a CFRoute created in the appropriate namespace with the specified FQDN mapped to `app1`.
```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

## Happy Path (Route exists but is not mapped to app)
**GIVEN** I have a cluster with a cfdomain already created for "example.com" and a manifest that specifies a route that already exists
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    routes:
    - my-host.example.com
```
**THEN I** I see the CFRoute with the specified FQDN updated to be mapped to `app1`.
```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

### Unhappy Path
**GIVEN** I have a cluster and a manifest that specifies an invalid route (E.G. no domain is yet created; note we will eventually have error cases with no-route and random-route here as well)
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    default-route: true
```
**THEN I** I see the CFRoute with the specified FQDN is **NOT** created.
```
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json

{
   "errors": [
      {
         "detail": "Manifest contains invalid attributes",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

### Dev Notes

* We want the manifest to function the same as the individual endpoints for various actions it can take. Try and factor out logic into reusable pieces where possible. The main difference here should be in the request parsing layer.
* Much of the logic for route manifest apply is in https://github.com/cloudfoundry/cloud_controller_ng/blob/a63cfe80d92e8f153db89d10963f10f9173a2f69/app/actions/app_apply_manifest.rb#L88-L121
* Only support the first route in the routes field for now and ignore related unsupported fields. We will follow up with further field support in separate issues.
* Only support the first cfDomain as the default app domain for now. We will follow up with explicit configuration of the api for default app domains.

**Comment by gnovv** [comment]
From [CCNG docs](https://github.com/cloudfoundry/cloud_controller_ng/blob/d8f79ec2dbecc75e31be9766d530eb4ffa4e23ad/docs/v3/source/includes/resources/manifests/_object.md.erb#L95):
```
**default-route** | _boolean_ | If true, a route for the app will be created using the app name as the hostname and the containing organization's default domain as the domain; if `routes` is specified, if the app already has routes, or if `no-route` is specified, this field is ignored regardless of its value
```
So default-route is only in-play if other route fields in the yaml are not present, or if the app has any routes already

**Comment by gnovv** [comment]
For now we punted on determining the default domain. 
The current implementation assumes it to be the oldest created Domain.
