### ISSUE TITLE
[Feature]: Platform Operator can delete a space

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/cf-k8s-controllers#379]
### Background

**As a** Platform Operator
**I want** to delete a space
**So that** can easily clean up all of the CFApps, CFRoutes CFPackages, etc. in that space

### Acceptance Criteria

**GIVEN** A deployed cf-k8s installation, with an org, a space, and one or more pushed applications
**WHEN I** `cf delete-space <space-name>`
**THEN I** can observe that the namespace for the space along with all of the applications and their dependent objects have been cleaned up.

### Dev Notes

* Need to retrieve org guid -> may be annotated or may require digging.

Some preliminary findings:

`kubectl delete ns $(cf space s --guid)` doesn't work–HNC disallows direct deletion of namespaces

`kubectl delete subns $(cf space s --guid) -n $(cf org o --guid)` *does* work, and deletes the namespace along with all associated routes, apps, packages, builds, etc. etc.

After discussion with Eric, we should pursue the easy implementation first (putting this logic into the API Shim) and possibly pursue creation of a CFSpace custom resource later outside the context of this story. 

Definition of deleted: k8s api accepts subns deletion request. Do not need to check for resource deletion (within subns).

**Comment by gnovv** [comment]
for 403 failure :
```
REQUEST: [2022-01-10T16:02:48-07:00]
DELETE /v3/spaces/9ed0bece-8e24-4d9f-9350-49f5762b9e33 HTTP/1.1
Host: api.cat-lasher.capi.land
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/8.0.0+e8d41cf8e.2021-09-16 (go1.16.6; amd64 darwin)
[application/json Content Hidden]

RESPONSE: [2022-01-10T16:02:48-07:00]
HTTP/1.1 403 Forbidden
Content-Type: application/json; charset=utf-8
Date: Mon, 10 Jan 2022 23:02:48 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-B3-Spanid: 4b5b22e40eba229103442e3ac1fc9d69
X-B3-Traceid: 4b5b22e40eba229103442e3ac1fc9d69
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.012414
X-Vcap-Request-Id: 6f103d3c-2296-4cdd-4722-be5614136ce7::be69bf1d-c65f-4d98-a9af-3ab0f63bb3fb
X-Xss-Protection: 1; mode=block
{
  "errors": [
    {
      "code": 10003,
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized"
    }
  ]
}


You are not authorized to perform the requested action
```

**Comment by gcapizzi** [comment]
I see this implementation does not use a user client to perform the deletion: I have added #438 to address this.
