### ISSUE TITLE
[Explore]: CFOrg and CFSpace custom resources

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/cf-k8s-controllers#382]
### Background

Consider creating CFOrg and CFSpace resources with associated controllers to allow management of orgs and spaces directly through `kubectl`.

The current stack has nontrivial logic in the API shim that would make it difficult to manage orgs and spaces through k8s. 

For example:
- we add kpack & eirini service accounts to each space after it gets created by HNC.
- when there are spaces in an org, the hierarchy object in each org needs to be modified after creation (or before deletion) to allow cascading deletes before the SubNamespaceAnchor for the org can be deleted.

We'd like to move this logic into the controller layer and make the API shim as dumb as possible.

This would also give us some insulation if we decide later to replace HNC with something more lightweight.

### Acceptance Criteria

We've written a proposal describing the changes we'd like to make, and solicited feedback,
Or
We've discovered that this is a bad idea, and documented the reasons why in comments below.

### Dev Notes

* Do we still want to use HNC if we decide the CRs are the correct path? This is a follow-on later and not required for this A/C.
* Check in at 2 days to see how HNC explorations are shaping up.

**Comment by julian-hj** [comment]
Past proposals & explorations:
- https://github.com/cloudfoundry/cf-crd-explorations/issues/69
- https://docs.google.com/document/d/1Pftj2RFayUPV4xc58efLI-0_m4wLLJWy7YhdJwRfu1Q/edit#heading=h.drik4ws976b7

**Comment by matt-royal** [comment]
The proposal was approved: https://docs.google.com/document/d/18RU-ZMookwjdpD-IJAVhzCyU1boF8pGuZEHAgpMs3Us/edit#heading=h.ywce4jce6q31
