### ISSUE TITLE
[Feature]: App Developer/Operator can fetch user-set environment variables for an app with `cf env APP-NAME`

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/cf-k8s-controllers#411]
### Blockers/Dependencies

N/A

### Background

**As a** App developer/operator using the cf cli
**I want** run `cf env`
**So that** I can view all the env variable for an app

We suspect this entails implementing the `GET v3/apps/<app-guid>/env` endpoint. [V3 API docs reference](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#get-environment-for-an-app)

### Acceptance Criteria

**GIVEN** I have an app pushed with some environment variables
**WHEN I** I run `cf env`
**THEN I** see all the environment variables set for the app

---

## Happy Path

**WHEN I** make the following request to GET v3/apps/<app-guid>/env
```
curl "https://api.example.org/v3/apps/[guid]/env" \
  -X GET \
  -H "Authorization: bearer [token]"
```

**THEN I** get the following response

```
{
  "staging_env_json": {},
  "running_env_json": {},
  "environment_variables": {
    "RAILS_ENV": "production"
  },
  "system_env_json": {},
  "application_env_json": {}
}
```

### Dev Notes
* Add Auth
* Spin out a chore to e2e test this functionality
* Consider having a common code path for generating the env vars between this and the LRP-generating code. That way, as we add additional env var they will show up here as well without extra work
* https://github.com/cloudfoundry/cf-k8s-controllers/blob/0d1b33880e674793257610e7f8e46dabe48d373a/controllers/controllers/workloads/cfprocess_controller.go#L179
* https://github.com/cloudfoundry/cloud_controller_ng/blob/cf3a1b37483c97132d89c60762e6100f9b10f2dc/app/presenters/v3/app_env_presenter.rb#L6

**Comment by matt-royal** [comment]
WIP for this is on the branch `issues/411`
