### ISSUE TITLE
[Feature]: Developers should only be able to get the current droplet for apps they have access to

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#440]
### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

### Acceptance Criteria

**GIVEN** two spaces `space1` and `space2` exist
**AND** `app1` exists in `space1`
**AND** `app2` exists in `space2`
**AND** `user` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`

1. **WHEN I** [get the current droplet](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#get-current-droplet) for `app1` as `user`
  **THEN I** see it working

1. **WHEN I** get the current droplet for `app2` as `user`
  **THEN I** get the following response:
  ```
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10010,
        "title": "CF-ResourceNotFound",
        "detail": "App not found"
      }
    ]
  }
  ```

**Comment by kieron-dev** [comment]
@gcapizzi I think this should be returning a 404 rather than a 403 on failure

**Comment by gcapizzi** [comment]
@kieron-dev I have updated acceptance, still not 100% sure about the title and description (CC has *many* 404 variants) but this should do for now!

**Comment by kieron-dev** [comment]
Switched 'detail' in description to 'Droplet not found' after trying on cf-on-vms

**Comment by kieron-dev** [comment]
> Switched 'detail' in description to 'Droplet not found' after trying on cf-on-vms

Take it all back! Wrong endpoint
