### ISSUE TITLE
[Feature]: Document the configuration of the CF admin user

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#444]
In order to become the CF admin, a user needs to be bound to the `cf-k8s-controllers-admin` `ClusterRole` in the root `cf` namespace. The binding will then propagate to all orgs and spaces and effectively give the admin user permissions on all orgs and spaces.

Let's document this procedure in our README.

**Comment by matt-royal** [comment]
We were low on stories, so we picked this up and submitted a PR
