### ISSUE TITLE
[Feature]: Developers should only be able to list processes for apps they have access to

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#447]
### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

### Acceptance Criteria

**GIVEN** two spaces `space1` and `space2` exist
**AND** `app1` exists in `space1`
**AND** `app2` exists in `space2`
**AND** `user` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`

1. **WHEN I** [list processes](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#list-processes-for-app) for `app1` as `user`
  **THEN I** see it working

1. **WHEN I** list processes for `app2` as `user`
  **THEN I** get the following response:
  ```
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10010,
        "title": "CF-ResourceNotFound",
        "detail": "App not found"
      }
    ]
  }
  ```

**Comment by kieron-dev** [comment]
I think this is another case where we get a not found when the user is not authorized. This is the response from curling the endpoint on mel-b:
```
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Mon, 24 Jan 2022 11:36:34 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-B3-Spanid: 0c4c5425f60d2118
X-B3-Traceid: 0c4c5425f60d2118
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.012748
X-Vcap-Request-Id: fe23b0b0-afb9-4a9d-65c4-4d3c465b959a::5bdf829e-976e-407d-8004-1c7b04424b5b
X-Xss-Protection: 1; mode=block

{
  "errors": [
    {
      "detail": "App not found",
      "title": "CF-ResourceNotFound",
      "code": 10010
    }
  ]
}
```

**Comment by gcapizzi** [comment]
Acceptance updated!
