### ISSUE TITLE
[Feature]: API Client can list service instances via `GET /v3/service_instances`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#457]
### Blockers/Dependencies

* Hard dependency: https://github.com/cloudfoundry/cf-k8s-controllers/issues/431
* Softer dependency: https://github.com/cloudfoundry/cf-k8s-controllers/issues/430

---

### Background

**Note:** User-provided Service Instance == UPSI

**As an** API Client
**I want** to be able to create list service instances and filter by name and space GUID
**So that** I can find a particular service instance by name

Check out the [Cloud Foundry User-Provided Service Instance docs](https://docs.cloudfoundry.org/devguide/services/user-provided.html) for more information on UPSIs.

---

### Listing service instances with no filters

**GIVEN** I have created some `CFServiceInstance` resources in namespaces that I have access to (in this example named `my-user-provided-instance` and `my-second-user-provided-instance` in spaces `5a84d315-9513-4d74-95e5-f6a5501eeef7` and `7a535078-9632-4671-87e1-5d002ff5fab0`).
**WHEN I** make the following request

```console
curl "https://api.example.org/v3/service_instances" \
  -X GET \
  -H "Authorization: bearer [token]"
```

**THEN I** get back a list of service instances

```json
{
  "pagination": {
    "total_results": 2,
    "total_pages": 1,
    "first": {
      "href": "https://api.example.org/v3/service_instances?page=1&per_page=50"
    },
    "last": {
      "href": "https://api.example.org/v3/service_instances?page=1&per_page=50"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    {
      "guid": "88ce23e5-27c3-4381-a2df-32a28ec43133",
      "created_at": "2020-03-10T15:56:08Z",
      "updated_at": "2020-03-10T15:56:08Z",
      "name": "my-user-provided-instance",
      "tags": [],
      "type": "user-provided",
      "syslog_drain_url": null,
      "route_service_url": null,
      "last_operation": {
        "type": "update",
        "state": "succeeded",
        "description": "Operation succeeded",
        "updated_at": "2020-03-10T15:59:32Z",
        "created_at": "2020-03-10T15:59:29Z"
      },
      "relationships": {
        "space": {
          "data": {
           "guid": "5a84d315-9513-4d74-95e5-f6a5501eeef7"
          }
        }
      },
      "metadata": {
        "labels": {},
        "annotations": {}
      },
      "links": {
        "self": {
          "href": "https://api.example.org/v3/service_instances/88ce23e5-27c3-4381-a2df-32a28ec43133"
        },
        "space": {
          "href": "https://api.example.org/v3/spaces/5a84d315-9513-4d74-95e5-f6a5501eeef7"
        },
        "credentials": {
          "href": "https://api.example.org/v3/service_instances/88ce23e5-27c3-4381-a2df-32a28ec43133/credentials"
        },
        "service_credential_bindings": {
          "href": "https://api.example.org/v3/service_credential_bindings?service_instance_guids=88ce23e5-27c3-4381-a2df-32a28ec43133"
        },
        "service_route_bindings": {
          "href": "https://api.example.org/v3/service_route_bindings?service_instance_guids=88ce23e5-27c3-4381-a2df-32a28ec43133"
        }
      }
    },
    {
      "guid": "0deb7840-23a0-4f4d-8042-71ebac49a7bd",
      "created_at": "2020-03-10T15:56:08Z",
      "updated_at": "2020-03-10T15:56:08Z",
      "name": "my-second-user-provided-instance",
      "tags": [],
      "type": "user-provided",
      "syslog_drain_url": null,
      "route_service_url": null,
      "last_operation": {
        "type": "update",
        "state": "succeeded",
        "description": "Operation succeeded",
        "updated_at": "2020-03-10T15:59:32Z",
        "created_at": "2020-03-10T15:59:29Z"
      },
      "relationships": {
        "space": {
          "data": {
           "guid": "7a535078-9632-4671-87e1-5d002ff5fab0"
          }
        }
      },
      "metadata": {
        "labels": {},
        "annotations": {}
      },
      "links": {
        "self": {
          "href": "https://api.example.org/v3/service_instances/0deb7840-23a0-4f4d-8042-71ebac49a7bd"
        },
        "space": {
          "href": "https://api.example.org/v3/spaces/7a535078-9632-4671-87e1-5d002ff5fab0"
        },
        "credentials": {
          "href": "https://api.example.org/v3/service_instances/0deb7840-23a0-4f4d-8042-71ebac49a7bd/credentials"
        },
        "service_credential_bindings": {
          "href": "https://api.example.org/v3/service_credential_bindings?service_instance_guids=0deb7840-23a0-4f4d-8042-71ebac49a7bd"
        },
        "service_route_bindings": {
          "href": "https://api.example.org/v3/service_route_bindings?service_instance_guids=0deb7840-23a0-4f4d-8042-71ebac49a7bd"
        }
      }
    }
  ]
}
```

---

### Listing service instances and filtering by name

**GIVEN** I have created some `CFServiceInstance` resources in namespaces that I have access to (in this example named `my-user-provided-instance` and `my-second-user-provided-instance` in spaces `5a84d315-9513-4d74-95e5-f6a5501eeef7` and `7a535078-9632-4671-87e1-5d002ff5fab0`).
**WHEN I** make the following request

curl "https://api.example.org/v3/service_instances?names=my-user-provided-instance" \
  -X GET \
  -H "Authorization: bearer [token]"

**THEN I** only get the service instance named `my-user-provided-instance` in the response. If we make another instance named `my-user-provided-instance` in a different namespace that we have access to, then we'd expect to get it back as well.

---

### Listing service instances and filtering by space

**GIVEN** I have created some `CFServiceInstance` resources in namespaces that I have access to (in this example named `my-user-provided-instance` and `my-second-user-provided-instance` in spaces `5a84d315-9513-4d74-95e5-f6a5501eeef7` and `7a535078-9632-4671-87e1-5d002ff5fab0`).
**WHEN I** make the following request

curl "https://api.example.org/v3/service_instances?space_guids=7a535078-9632-4671-87e1-5d002ff5fab0" \
  -X GET \
  -H "Authorization: bearer [token]"

**THEN I** only get the service instances in the `7a535078-9632-4671-87e1-5d002ff5fab0` space in the response. If we make another instance  in that space then we'd expect to get it back in the response as well.

---

### Listing service instances and filtering by name **and** space

**GIVEN** I have created some `CFServiceInstance` resources in namespaces that I have access to (in this example named `my-user-provided-instance` and `my-second-user-provided-instance` in spaces `5a84d315-9513-4d74-95e5-f6a5501eeef7` and `7a535078-9632-4671-87e1-5d002ff5fab0`).
**WHEN I** make the following request

curl "https://api.example.org/v3/service_instances?names=my-user-provided-instance&space_guids=5a84d315-9513-4d74-95e5-f6a5501eeef7" \
  -X GET \
  -H "Authorization: bearer [token]"

**THEN I** only get the service instance named `my-user-provided-instance` from the `5a84d315-9513-4d74-95e5-f6a5501eeef7` space back in the response.

---

### No visible service instances

**GIVEN** `CFServiceInstance` resources exist in a namespace that I don't have access to (and no instances exist in namespaces I do have access to)
**WHEN I** make the following request

```console
curl "https://api.example.org/v3/service_instances" \
  -X GET \
  -H "Authorization: bearer [token]"
```

**THEN I** Get back a `200` response, but with an empty list of service instance resources

---

### Dev Notes

* Related Exploration: https://github.com/cloudfoundry/cf-k8s-controllers/issues/367
* [UPSI Proposal Doc](https://docs.google.com/document/d/1pi7u2zH07oeKS6TalWhzsnFPwbCy44SrvPGRMfomops/edit#heading=h.9w70n3ykktw2)
* v3 CF docs: https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#list-service-instances
* CCNG presenter code: https://github.com/cloudfoundry/cloud_controller_ng/blob/50c32a0282cbd1b9ba6d06e46971a5244205be13/app/presenters/v3/service_instance_presenter.rb
* Add RBAC/auth for this endpoint as part of this work

**Comment by gnovv** [comment]
@tcdowney 
`cf curl /v3/service_instances` works but not `cf s`
```
$ cf curl /v3/service_instances?names=my-db-mine | jq .
{
  "pagination": {
    "total_results": 1,
    "total_pages": 1,
    "first": {
      "href": "http://localhost/v3/service_instances?names=my-db-mine"
    },
    "last": {
      "href": "http://localhost/v3/service_instances?names=my-db-mine"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    {
      "name": "my-db-mine",
      "guid": "cfa88244-4748-49ba-addf-e9cccff72cfc",
      "type": "user-provided",
      "tags": [],
      "last_operation": {
        "created_at": "2022-01-27T22:06:27Z",
        "updated_at": "2022-01-27T22:06:27Z",
        "description": "Operation succeeded",
        "state": "succeeded",
        "type": "create"
      },
      "route_service_url": null,
      "syslog_drain_url": null,
      "created_at": "2022-01-27T22:06:27Z",
      "updated_at": "2022-01-27T22:06:27Z",
      "relationships": {
        "space": {
          "data": {
            "guid": "c26390af-0681-4f4a-90d4-8bcde0285249"
          }
        }
      },
      "metadata": {
        "labels": {},
        "annotations": {}
      },
      "links": {
        "self": {
          "href": "http://localhost/v3/service_instances/cfa88244-4748-49ba-addf-e9cccff72cfc"
        },
        "space": {
          "href": "http://localhost/v3/spaces/c26390af-0681-4f4a-90d4-8bcde0285249"
        },
        "credentials": {
          "href": "http://localhost/v3/service_instances/cfa88244-4748-49ba-addf-e9cccff72cfc/credentials"
        },
        "service_credential_bindings": {
          "href": "http://localhost/v3/service_credential_bindings?service_instance_guids=cfa88244-4748-49ba-addf-e9cccff72cfc"
        },
        "service_route_bindings": {
          "href": "http://localhost/v3/service_route_bindings?service_instance_guids=cfa88244-4748-49ba-addf-e9cccff72cfc"
        }
      }
    }
  ]
}
```

```
$ cf s -v
REQUEST: [2022-01-27T14:07:29-08:00]
GET /whoami HTTP/1.1
Host: localhost
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/8.1.0+034d929d7.2022-01-03 (go1.16.6; amd64 darwin)
[application/json Content Hidden]

RESPONSE: [2022-01-27T14:07:30-08:00]
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 27 Jan 2022 22:07:31 GMT
Server: envoy
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 1404
{
  "kind": "User",
  "name": "kubernetes-admin"
}


Getting service instances in org o / space s as kubernetes-admin...

REQUEST: [2022-01-27T14:07:30-08:00]
GET /v3/service_instances?fields%5Bservice_plan.service_offering.service_broker%5D=guid%2Cname&fields%5Bservice_plan.service_offering%5D=guid%2Cname%2Crelationships.service_broker&fields%5Bservice_plan%5D=guid%2Cname%2Crelationships.service_offering&order_by=name&per_page=5000&space_guids=c26390af-0681-4f4a-90d4-8bcde0285249 HTTP/1.1
Host: localhost
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/8.1.0+034d929d7.2022-01-03 (go1.16.6; amd64 darwin)
[application/json Content Hidden]

RESPONSE: [2022-01-27T14:07:30-08:00]
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Thu, 27 Jan 2022 22:07:31 GMT
Server: envoy
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 0
{
  "errors": [
    {
      "code": 10005,
      "detail": "The query parameter is invalid: Valid parameters are: 'names, space_guids'",
      "title": "CF-BadQueryParameter"
    }
  ]
}


The query parameter is invalid: Valid parameters are: 'names, space_guids'
```

**Comment by akrishna90** [comment]
@tcdowney We assumed the list endpoint was in service of the `cf services` command. Look like we it might have been for `cf bind-service`. We ultimately verified the behaviour using `cf curl`.

**Comment by tcdowney** [comment]
Yeah this one is for `cf bind-service`, `cf services` needs more filter support as you've found out.
