### ISSUE TITLE
[Chore]: Automated test for the `cf api` command

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-k8s-controllers#482]
### Background

At the moment we are missing a real end-to-end test suite for the cf-k8s venture. This is bad, because it means we are not constantly checking that the cf cli works against the cf-k8s-api (and we have made some k8s-specific changes to the cf cli already). After some discussion we have decided that it is not practical to reuse the [CATS](https://github.com/cloudfoundry/cf-acceptance-tests) test suite, since the cf-k8s project will not be mature enough to run it any time soon and since cf-k8s might end up behaving slightly differently to classic cf. That's why it has been decided to write a new test suite that test the cf-k8s behaviour through the cf cli.

This is the first chore in a track of chores that will help us fill in that gap. 

### Action to take

Create a true end-to-end test suite:
- create a new test suite under `cf-k8s-controllers/test/e2e`. We might nickname the test suite for disambiguation (`kats` sounds like a good nickname, but feel free to come up with another one). 
- add a make target for the new test suite
- the test suite should take the cli path as an argument
- check cli version in before suite and fail if it is too old (older than `v.8.1.0`)
- add the new test suite to the `check-everything` script
- write a test that performs `cf api` against the  cf-k8s kind deployment
  - this is enough to showcase cli testing
  - we should validate that cf-k8s is enabled in the cli config (possibly a unique temp file for each test)

### Impact

We are testing the cf-k8s project end-to-end in a periodic and automated fashion.

### Dev Notes
While writing the end-to-end tests let's try and reuse as much as possible from the original CATS:
- there is a nice [utility](https://github.com/cloudfoundry/cf-acceptance-tests/blob/7d951cae745f41087f2e96103f239823c7814846/docker/private_docker_lifecycle.go#L54-L56) that can run arbitrary cf commands. Looks like it can handle input and sanitization of sensitive data.
- there are some [helpers](https://github.com/cloudfoundry/cf-acceptance-tests/blob/7d951cae745f41087f2e96103f239823c7814846/tasks/task.go#L99-L101) that can log you in as an arbitrary user
- the [sample cf apps](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop/assets) are defined there
- keep looking for more reusable bits. This has the added benefit that the new suite will look similar to the CATS and it this might make it easier to merge it back if needed.

**Comment by davewalter** [comment]
Would be better if this new test suite is created as a sibling to the existing end-to-end suite, instead of as a child suite? If I understand correctly, some of the setup for the current `e2e` suite only works with Kind clusters, and I think it would be good if users can bring their own cluster (of any type), deploy cf-k8s-controllers and run the new `acceptance` test suite, much as CATs is used today with CF for VMs.

**Comment by georgethebeatle** [comment]
Closing this chore, since a [smoke suite](https://github.com/cloudfoundry/cf-k8s-controllers/tree/main/tests/smoke) seems to have appeared and we can use it as a basis for an acceptance suite.
