### ISSUE TITLE
Chore: Make CFDomain Namespaced resource type

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/cf-k8s-controllers#490]
### Background

Current, CFDomains are a Cluster scope resource. To support private domains in the future, this should be changed to be a Namespaced resource. Shared domains would be in the root namespace.

### Action to take

Update CFDomain CRD to be Namespaced. Resolve any resulting issues that arise from this.

The `cfdomain_types.go` file contains the definition of the resource. This should be updated, then controller-gen should be re-run.

### Impact

This will enable future development of private domains. While not critical now, updating the resource to be namespaced will reduce future risk.

### Dev Notes
* Needed to support private domains: https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#private-domains
* Consider RBAC (we believe we currently use privileged clients, so it probably won't matter yet)
* Ensure that we're including the namespace in DomainRefs

**Comment by akrishna90** [comment]
To Address **`Ensure that we're including the namespace in DomainRefs`**

- **Controller changes**
   - [ ] Change `DomainRef` on the CFRoute to be `v1.ObjectReference`
   - [ ] Update `CFRouteController` to fetch CFDomain using `NamespaceName`
 
- **API Changes**
   - [ ] Change GetDomain Repo method to query with `namespace` info
   - [ ] Update all callers to this method to pass the `namespace` ( which is `rootNamespace` indicated in config)
