### ISSUE TITLE
[Explore]: Get logs with k8s client-go

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/cf-k8s-controllers#493]
### Background

To provide users basic logs, cf defines the log cache api and a configuration option to specify the log cache endpoint. Log cache is responsible for returning the logs in the cf envelope format, so our dependency on the backing implementation for this functionality has also motivated an explore for handling the conversion of kubectl logs to cf envelopes as a potential workaround to using log cache itself.

Let's replicate the solution for fetching kubectl logs in kpack: leveraging the kubernetes client-go to fetch the existing logs api resource. https://github.com/pivotal/kpack/blob/main/pkg/logs/build_logs.go to fetch logs for a particular app guid. Much like kubectl logs, the caller must select the containers for which they would like to view logs, so we'll need to select the relevant pods/containers based on the given app guid. Don't worry about the app instance for this spike, just fetch all the logs for the app.

### Acceptance Criteria

Spike branch with examples of the k8s client-go pulling logs for an app and for its build pod.

Note any RBAC concerns that arise for ownership/access to any of the containers by a user client.

### Number of days this exploration is expected to take. This is what is “pointed”.

2 Days

### Dev Notes

There's no need to match the envelope format for this story. That will be handled later.

There's an existing endpoint for returning logs, but it always returns blank: https://github.com/cloudfoundry/cf-k8s-controllers/blob/main/api/apis/log_cache_handler.go#L29

**Comment by akrishna90** [comment]
@davewalter and I have a working [spike implementation](https://github.com/cloudfoundry/cf-k8s-controllers/tree/spike-log-cache-api) that returns logs for an app and its `latest` build pod

-  We leveraged Kpack's existing [log library](https://github.com/pivotal/kpack/blob/9c150c70cf74f3b548d1b1616f857747b4c05e23/pkg/logs/build_logs.go) to fetch logs for build pods
-  We consumed the Kubernetes client-go's [GetLogs](https://github.com/kubernetes/client-go/blob/664b1a6c8ce9c92ce65bef3f9833b402449c98d2/kubernetes/typed/core/v1/pod_expansion.go#L69) to fetch logs for application pods
- In terms of permissions, we had to grant `get` access to `pods/log` resource.
- The logs returned (see below for the api response) do **NOT** have any timestamp information and they are **NOT** in envelope format - (we will explore these in a different story)
- If we need to target specific containers for logs on a Pod, we can do so by specifying them within `corev1.PodLogOptions` when we make the [GetLogs](https://github.com/kubernetes/client-go/blob/664b1a6c8ce9c92ce65bef3f9833b402449c98d2/kubernetes/typed/core/v1/pod_expansion.go#L69) function call.

#### Spike API response for log-cache endpoint
```
ak $ curl http://localhost/api/v1/read/43e39865-5b5e-42a0-b269-3e8df7e639e1 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2535    0  2535    0     0   1777      0 --:--:--  0:00:01 --:--:--  1777
{
  "envelopes": {
    "batch": [
      "\u001b[0;36m===> PREPARE",
      "\u001b[0mBuild reason(s): CONFIG",
      "CONFIG:",
      "\tresources: {}",
      "\t\u001b[31m-\u001b[0m \u001b[31msource: {}\u001b[0m",
      "\t\u001b[32m+\u001b[0m \u001b[32msource:\u001b[0m",
      "\t\u001b[32m+\u001b[0m \u001b[32m  registry:\u001b[0m",
      "\t\u001b[32m+\u001b[0m \u001b[32m    image: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages/783e2555-ec8e-436e-bd13-cbae003ce956@sha256:889e4d2c16f8ea513d90104bbc0fcb051bb293fa1123f55461817aae84442398\u001b[0m",
      "\t\u001b[32m+\u001b[0m \u001b[32m    imagePullSecrets:\u001b[0m",
      "\t\u001b[32m+\u001b[0m \u001b[32m    - name: image-registry-credentials\u001b[0m",
      "Loading secret for \"localregistry-docker-registry.default.svc.cluster.local:30050\" from secret \"image-registry-credentials\" at location \"/var/build-secrets/image-registry-credentials\"",
      "Pulling localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages/783e2555-ec8e-436e-bd13-cbae003ce956@sha256:889e4d2c16f8ea513d90104bbc0fcb051bb293fa1123f55461817aae84442398...",
      "Successfully pulled localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages/783e2555-ec8e-436e-bd13-cbae003ce956@sha256:889e4d2c16f8ea513d90104bbc0fcb051bb293fa1123f55461817aae84442398 in path \"/workspace\"",
      "\u001b[0;36m===> ANALYZE",
      "\u001b[0mPrevious image with name \"localregistry-docker-registry.default.svc.cluster.local:30050/cf-k8s-controllers/kpack/images/6b6439f7-a3d6-4f1f-9c4c-0d599ffe24c3\" not found",
      "\u001b[0;36m===> DETECT",
      "\u001b[0m5 of 10 buildpacks participating",
      "paketo-buildpacks/ca-certificates 3.0.1",
      "paketo-buildpacks/node-engine     0.11.2",
      "paketo-buildpacks/npm-install     0.6.2",
      "paketo-buildpacks/node-module-bom 0.2.0",
      "paketo-buildpacks/npm-start       0.6.1",
      "\u001b[0;36m===> RESTORE",
      "\u001b[0m\u001b[0;36m===> BUILD",
      "\u001b[0m\u001b[34m\u001b[0m",
      "\u001b[34m\u001b[1mPaketo CA Certificates Buildpack\u001b[0m\u001b[34m 3.0.1\u001b[0m",
      "  \u001b[34;2;3mhttps://github.com/paketo-buildpacks/ca-certificates\u001b[0m",
      "  \u001b[34mLaunch Helper\u001b[0m: \u001b[33mContributing\u001b[0m to layer",
      "\u001b[2m    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper\u001b[0m",
      "Paketo Node Engine Buildpack 0.11.2",
      "  Resolving Node Engine version",
      "    Candidate version sources (in priority order):",
      "                -> \"\"",
      "      <unknown> -> \"\"",
      "",
      "    Selected Node Engine version (using ): 16.13.1",
      "",
      "  Executing build process",
      "    Installing Node Engine 16.13.1",
      ""
    ]
  }
}
```

**Comment by gcapizzi** [comment]
Closing this as it looks like the experiment is complete, feel free to reopen it otherwise!
