### ISSUE TITLE
[Bug] Roles are not set up (i.e. propagated) immediately after `create org` or `create space` API call returns

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/cf-k8s-controllers#538]
This causes lots of flakes in the E2E tests

**Comment by kieron-dev** [comment]
It does not appear to be possible to determine when propagation into a new namespace is complete in the HNC design.

When a new namespace is added to the HN hierarchy, e.g. by the [anchor reconciler creating a namespace](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/550d0c85e42b60605f8518267cd8299580447839/internal/anchor/reconciler.go#L119) corresponding to a new subnamespaceanchor, the [hierarchyconfig reconciler](//github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/internal/hierarchyconfig/reconciler.go) will trigger. When this notices a change, it [enqueues](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/550d0c85e42b60605f8518267cd8299580447839/internal/hierarchyconfig/reconciler.go#L758) all objects to be propagated in the namespace to the [object reconciler](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/550d0c85e42b60605f8518267cd8299580447839/internal/objects/reconciler.go#L115-L127).

Once the hierarchy config reconciler has enqueued the required objects, the connection between those objects and the namespace creation event is lost. The object reconcilers just process their queues and at some point those enqueued from the namespace creation event will be reconciled. There is no point where we can know all the object reconcilers are done with objects from the creation and it is appropriate to update a status on the anchor, say.

So I don't think a modification to HNC is going to be possible for this issue.

**Comment by kieron-dev** [comment]
If we implement code to wait for rolebindings of the current user to propagate to the new namespace on namespace creation, there are also problems.

Suppose the current user is has only the org-manager role. This [permits them space creation](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#create-a-space) on their org. The cluster role allowing this gives create permission on subnamespace anchors. This role should not be bound in the new namespace, as that represents a space, and we should not allow subnamespaces of a space. So we would be waiting for a role that would never be propagated.

We might think about checking if a certain admin rolebinding was propagated. But there can be many admins, and the admin user might well be changed during a create namespace operation, so there's a potential for a race where we wait for a role binding that won't be propagated.

So I'm not sure we have a solution to this at present.

**Comment by gcapizzi** [comment]
This is temporarily fixed by #760 - not perfect but good enough for now!
