### ISSUE TITLE
[Feature]: Developers should only be able to get builds associated to apps they have access to

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#542]
### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

### Acceptance Criteria

**GIVEN** two spaces `space1` and `space2` exist
**AND** `app1` exists in `space1`
**AND** `build1` is a build belonging to `app1`
**AND** `app2` exists in `space2`
**AND** `build2` is a build belonging to `app2`
**AND** `user` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`

1. **WHEN I** [get `build1`](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#get-a-build) as `user`
  **THEN I** see it working

1. **WHEN I** get `build2` as `user`
  **THEN I** get the following response:
  ```
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10010,
        "title": "CF-ResourceNotFound",
        "detail": "App not found"
      }
    ]
  }
  ```

**Comment by kieron-dev** [comment]
The error message will be build not found, rather than app not found.
