### ISSUE TITLE
[Bug]: Unable to delete invalid `CFRoute` when there is an existing `HTTPProxy` for the FQDN in another namespace

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#548]
### What happened?

I was validating https://github.com/cloudfoundry/cf-k8s-controllers/issues/380 and had an app with the same name pushed to two different orgs. Two different `CFRoutes` got created, but the route in `SECOND_ORG`/`SECOND_SPACE` was invalid since the `HTTPProxy` for its FQDN existing in `FIRST_ORG`/`FIRST_SPACE`.

`cf delete-org SECOND_ORG` got stuck with both namespaces in the `Terminating` state. I dug into it and found it was due to a lingering invalid `CFRoute`.

The logs in the `CFRouteController` said this:

```
1.6430607545114973e+09	INFO	controllers.CFRoute	Reconciling deletion of CFRoute/64ce5246-bbdd-432c-8649-b2547a5cc457
1.6430607545115876e+09	ERROR	controllers.CFRoute	existing proxy found in namespace 458d35bd-4c9b-4fd2-bf2d-f0deb162a33b	{"error": "found existing HTTPProxy with FQDN node2.k8s.tim.migration.quest in another space"}
code.cloudfoundry.org/cf-k8s-controllers/controllers/controllers/networking.(*CFRouteReconciler).finalizeCFRoute
	/workspace/controllers/controllers/networking/cfroute_controller.go:188
code.cloudfoundry.org/cf-k8s-controllers/controllers/controllers/networking.(*CFRouteReconciler).Reconcile
	/workspace/controllers/controllers/networking/cfroute_controller.go:95
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
1.6430607545116537e+09	ERROR	controller.cfroute	Reconciler error	{"reconciler group": "networking.cloudfoundry.org", "reconciler kind": "CFRoute", "name": "64ce5246-bbdd-432c-8649-b2547a5cc457", "namespace": "2da11b9d-2478-40a6-9f6f-47c1120dc48e", "error": "found existing HTTPProxy with FQDN node2.k8s.tim.migration.quest in another space"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
``` 

### What you expected to happen

I expected the `CFRoute` to delete successfully even though it was invalid.

### Acceptance Criteria

GIVEN I have a valid `CFRoute` in a separate org/space (`org1`) that shares the same FQDN as an invalid `CFRoute` in the org/space that I'm try to delete (`org2`)
WHEN I `cf delete-org org2`
THEN I see the corresponding namespaces for that org are successfully deleted

---

### How to reproduce it (as minimally and precisely as possible)

1. `cf create-org org1 && cf create-space -o org1 space1 && cf target -o org1 -s space1`
2. `cf push node` (with `default-route: true` in its manifest)
3. `cf create-org org2 && cf create-space -o org2 space2 && cf target -o org2 -s space2`
4. `cf push node` (with `default-route: true` in its manifest)
5. `cf delete-org org2`

### Environment

Revision of codebase: b49005846c4b6a186cb0aa9b034bdcc846e75725
Kubernetes version (use `kubectl version`): N/A
Cloud provider or hardware configuration: GKE
Others:

### Dev Notes
In addition to validating the delete flow already detailed in the bug report, also check the intermediate state of pushing an app to multiple orgs with multiple routes for unexpected errors. If we're seeing unexpected httpproxy logs on delete, we may also be incorrectly creating a duplicate httpproxy in the first place.

**Comment by akrishna90** [comment]
@tcdowney - #730 added validation to restrict users from creating routes with the same FQDN. 

This bug is no longer reproducible using the steps mentioned on this bug. When we try to `cf push` an `app` with the "same" name in `org2` & `space2`, it now fails with `HTTP 500 status`. Looking at the api-logs, I see
```
ERROR    SpaceManifestHandler    Error applying manifest    {"error": "createOrUpdateRoutes: Route duplicate: admission webhook \"vcfroute.networking.cloudfoundry.org\" denied the request: {\"code\":4,\"message\":\"Route with same FQDN and path exists\"}"}
```
Is there other ways of causing fqdn collisions?  

Side Note - We might want to improve our error message here to inform user that a duplicate route with the same FQDN exists instead of saying "Unknown Error Occurred"

**Comment by tcdowney** [comment]
@akrishna90 yeah I don't think there is an easy way for users to get themselves into this state anymore, but I think we can still trigger the buggy behavior in the controller and should tighten that up anyway.

Here's something we can try (I haven't tested this on an env myself):

So you know how we get two `HTTPProxy` resources when you create a route and one corresponds with the FQDN? I think if we apply that fqdn `HTTPProxy` to another namespace and then delete the one in the correct namespace the `CFRoute` will fail to delete. I know this is a bit contrived, but I think that's similar to the internal state we had after those repro steps.

**Comment by tcdowney** [comment]
Oh yeah, regarding the side note. That's nice cause it's a new example error case we can use to help drive out :D https://github.com/cloudfoundry/cf-k8s-controllers/issues/699

My previous error got fixed by you on the default domain error handling story 😛

**Comment by Birdrock** [comment]
Unable to reproduce issue. Appears to be fixed.
