### ISSUE TITLE
[Feature]: Developers should only be able to get processes associated to apps they have access to

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#554]
### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

### Acceptance Criteria

**GIVEN** two spaces `space1` and `space2` exist
**AND** `app1` exists in `space1`
**AND** `process1` exists for `app1`
**AND** `app2` exists in `space2`
**AND** `process2` exists for `app2`
**AND** `user` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`

1. **WHEN I** [get `process1`](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#get-a-process) as `user`
  **THEN I** see it working

1. **WHEN I** get `process2` as `user`
  **THEN I** get the following response:
  ```
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10010,
        "title": "CF-ResourceNotFound",
        "detail": "Process not found"
      }
    ]
  }
  ```

**Comment by tcdowney** [comment]
@gcapizzi I think I heard during one of the sync calls that y'all have been folding in e2e test work into these stories? Is that true? Should we be doing some of the work for https://github.com/cloudfoundry/cf-k8s-controllers/issues/523 (at least the `GET /v3/processes/:guid` part) as part of this?

Also, just for confirmation, the two endpoints covered by this story are:
* `GET /v3/apps/:guid/processes/:type`
* `GET /v3/processes/:guid`

**Comment by gcapizzi** [comment]
I [doesn't look like](https://github.com/cloudfoundry/cf-k8s-controllers/blob/main/api/apis/app_handler.go#L26-L39) we implement `GET /v3/apps/:guid/processes/:type` yet, so we only need to work on `GET /v3/processes/:guid` for now. 

Yes we want to write end-to-end tests before changing the corresponding endpoint, #523 can be left to a no-op if nothing is left to backfill by the time we pick it up!

**Comment by gcapizzi** [comment]
Dragging this back to _Review in progress_, see [this comment](https://github.com/cloudfoundry/cf-k8s-controllers/pull/633#issuecomment-1036100687) for details!
