### ISSUE TITLE
[Chore]: NET::ERR_CERT_REVOKED on https://jetson.eirini.cf-app.com/

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-k8s-controllers#611]
### Background

Looks like Let's Encrypt Has revoked the cert of Eirini's Concourse

### Action to take

Investigate

### Impact

Eirini's CI has a valid certificate

**Comment by kieron-dev** [comment]
We connected to the concourse DB (instructions in the eirini private repo in the concourse README), and deleted the cert_cache entry for jetson.eirini.cf-app.com, according to this helpful issue: https://github.com/concourse/concourse/issues/8021
