### ISSUE TITLE
[Feature]: app developer can list domains for an organization

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/cf-k8s-controllers#663]
### Blockers/Dependencies

Dependent on making domains a namespaced resource. #490 

### Background

**As a** app developer
**I want** to be able to list domains for an organization
**So that** know which domains are available for my organization

### Acceptance Criteria

**GIVEN** I have an organization with domains
**WHEN I** make a request to the list domains for an organization end point
```
curl "https://api.example.org/v3/organizations/[guid]/domains" \
  -X GET \
  -H "Authorization: bearer [token]"
```
**THEN I** see the domains in a response like:
```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "pagination": {
    "total_results": 3,
    "total_pages": 2,
    "first": {
      "href": "https://api.example.org/v3/domains?page=1&per_page=2"
    },
    "last": {
      "href": "https://api.example.org/v3/domains?page=2&per_page=2"
    },
    "next": {
      "href": "https://api.example.org/v3/domains?page=2&per_page=2"
    },
    "previous": null
  },
  "resources": [
    {
      "guid": "3a5d3d89-3f89-4f05-8188-8a2b298c79d5",
      "created_at": "2019-03-08T01:06:19Z",
      "updated_at": "2019-03-08T01:06:19Z",
      "name": "test-domain.com",
      "internal": false,
      "router_group": { "guid": "5806148f-cce6-4d86-7fbd-aa269e3f6f3f" },
      "supported_protocols": ["tcp"],
      "metadata": {
        "labels": {},
        "annotations": {}
      },
      "relationships": {
        "organization": {
          "data": null
        },
        "shared_organizations": {
          "data": []
        }
      },
      "links": {
        "self": {
          "href": "https://api.example.org/v3/domains/3a5d3d89-3f89-4f05-8188-8a2b298c79d5"
        },
        "route_reservations": {
          "href": "https://api.example.org/v3/domains/3a5d3d89-3f89-4f05-8188-8a2b298c79d5/route_reservations"
        },
        "router_group": {
          "href": "https://api.example.org/routing/v1/router_groups/5806148f-cce6-4d86-7fbd-aa269e3f6f3f"
        }
      }
    },
  ]
}
```

### Dev Notes
* Note that we're returning domain resources from different namespaces than the org resource itself
* Validate user access to the org

**Comment by gnovv** [comment]
Discussing with @Birdrock and @tcdowney we will proceed with an initial implementation that simply lists all the shared domains, since it is not yet possible to create Domains under Organizations yet.

As a result, this DomainList for Org handler will use the exact same ListDomains Repo function in the implementation.
Adding support for Domains under specific Orgs will be later issue
