### ISSUE TITLE
[Feature]: API Client can see that kpack Image OwnerReferences are set upon creation

### ISSUE THREAD

**Issue by gnovv** [cloudfoundry/cf-k8s-controllers#69]
### Background

As an API Client
I want a CF Build to result in a kpack image with an OwnerRef that points to the CFBuild
So that I can cleanly delete a CFBuild and its child objects

### Acceptance Criteria

GIVEN that I am targeting a k8s cluster
AND that I have followed the README instructions to install the Controllers and set up the kpack Registry Credentials and staging CRs
WHEN I apply the example CFApp, CFPackage, and CFBuild resources in config/samples directory
THEN I should see all those operations succeed
WHEN I fetch the yaml for the kpack image CR after it is created by the build controller
THEN I should be able to see it contains an OwnerReference in its metadata so that it is deleted when the CFBuild is deleted

### Dev Notes

- Modify the BuildController where it creates the kpack image [here](https://github.com/cloudfoundry/cf-k8s-controllers/blob/a395af00d895d9975ad8ea1a90a14673ffd98ab2/controllers/workloads/cfbuild_controller.go#L148)
- The desired outcome is that when a CFBuild is deleted, its kpack image and kpack builds will also be deleted.

**Comment by tcdowney** [comment]
Closing: This was addressed in #226 and further validated in https://github.com/cloudfoundry/cf-k8s-controllers/pull/368.
