### ISSUE TITLE
[Chore] Copy Smoke Tests from cf-for-k8s

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-k8s-controllers#704]
### Background

In cf-for-k8s, we developed a small set of [smoke-tests](https://github.com/cloudfoundry/cf-for-k8s/blob/develop/tests/smoke/smoke_test.go) that exercised basic `cf push` functionality. It would be useful to have a similar set of tests for cf-k8s-controllers.

### Action to take

* Copy the `tests/smoke` directory from cf-for-k8s to cf-k8s-controllers.
* Delete the test that validates that docker apps can be pushed to the platform as we do not support them.
* Comment out the part of the test that verifies that application logs can be retrieved as we do not support log retrieval yet.

### Impact

Having a set of smoke tests will provide a fast way to validate a deployment of cf-k8s-controllers.

**Comment by gnovv** [comment]
This chore appears blocked on being able to login to cf noninteractively- tracked in this [issue](https://github.com/cloudfoundry/cf-k8s-controllers/issues/467)

**Comment by julian-hj** [comment]
It's a little bit gross, but this command appears to get the job done:

```
echo "1
1
1
" | KUBECONFIG=~/.kube/e2e.yml cf login
```
It would mean that you have to invoke bash to login, instead of invoking the cli directly.
