### ISSUE TITLE
[Feature]: Every user should be bound to the `cf_user` role in the root "cf" namespace

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#721]
### Background

We store [shared domains](https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains) as `CFDomain` resources in our root namespace. Since shared domains are available to users in all orgs of a CF deployment, we need a way to allow all users of the system to list and get them.

The best way to do this is to automatically assign a `cf_user` role to any user who gets assigned any role on the system, if they don't have it already. The `cf_user` role can be configured with permissions to get and list shared domains. Only admin can create shared domains.

### Acceptance Criteria

**GIVEN** `org` exists
**AND** `space` is in `org`
-  **AND** `user` has no roles yet
  **WHEN I** [assign any role](https://v3-apidocs.cloudfoundry.org/version/3.115.0/index.html#create-a-role) to `user` in `space` or `org`
    **THEN I** see the `cf_user` role has also been assigned to `user`
-  **AND** `user` already is a `cf_user`
  **WHEN I** assign any other role to `user` in `space` or `org`
    **THEN I** see it work
    **AND** `user` is still a `cf_user`

### Dev Notes

Some work in this direction [has already been done](https://cloudfoundry.slack.com/archives/C0297673ASK/p1645779601613699) to be able to write end-to-end tests for routes:
  - a [role](https://github.com/cloudfoundry/cf-k8s-controllers/blob/c15946522f9c0b569d65337a4d43ed0868487c2a/controllers/config/cf_roles/cf_root_namespace_user.yaml) has already been created and we could just rename it;
  - end-to-end tests are currently [explicitly creating the role](https://github.com/cloudfoundry/cf-k8s-controllers/blob/44fc30ded70277a49c0372df5229dcdb0ab9ba6f/api/tests/e2e/e2e_suite_test.go#L182-L201) in `BeforeSuite`, after this change that shouldn't be necessary anymore.

Don't attempt to address the cleanup of this role when other roles (such as OrgUser) are removed from a user.

Reach out to Matt if you need more context on this change.

**Comment by matt-royal** [comment]
Thank you for writing this up, @gcapizzi!
