### ISSUE TITLE
[Feature]: Developers should only be able to create manifest diffs for spaces they have access to

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#742]
#### Background

**As an** admin
**I want** to assign the `SpaceDeveloper` role to the users I trust
**So that** they can push apps to their spaces

### Acceptance Criteria

**GIVEN** two spaces `space1` and `space2` exist
**AND** `mgr` has a `RoleBinding` to the `SpaceManager` `ClusterRole` in `space1`
**AND** `dev` has a `RoleBinding` to the `SpaceDeveloper` `ClusterRole` in `space1`
* **WHEN I** [create a manifest diff](https://v3-apidocs.cloudfoundry.org/version/3.115.0/index.html#create-a-manifest-diff-for-a-space-experimental) for `space1` as `dev`
  **THEN I** see it working
* **WHEN I** create a manifest diff for `space1` as `mgr`
  **THEN I** get the following response:
  ```
  HTTP/1.1 403 Forbidden
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10003,
        "title": "CF-NotAuthorized",
        "detail": "You are not authorized to perform the requested action"
      }
    ]
  }
  ```
* **WHEN I** create a manifest diff for `space2` as `dev`
  **THEN I** get the following response:
  ```
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10010,
        "title": "CF-ResourceNotFound",
        "detail": "Space not found"
      }
    ]
  }
  ```

**Comment by gnovv** [comment]
@gcapizzi as far as we can tell, the 403 unauthorized case isn't possible to reach at the moment.

Manifests are not a CF CR with RBAC, so the only permissions in play here are used in the `GET Space call` [here](https://github.com/cloudfoundry/cf-k8s-controllers/blob/2312db9f197a2c5cb24baab67fa77051aff5180c/api/apis/space_manifest_handler.go#L85)

For now we will only support the Not-Found error case- let us know if you have any issues/comments here or on our PR

**Comment by gcapizzi** [comment]
@gnovv makes sense, given the endpoint is a no-op at the moment it's not a big deal!
