### ISSUE TITLE
[Chore]: Run tests in parallel

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/cf-k8s-controllers#85]
### Background

Now that we are using Ginkgo for tests, we could also make use of running tests in parallel the Ginkgo way when running `make test`.

### Action to take

* Revisit suites setup-tear-down, maybe use `SynchronizedBeforeSuite/SynchronizedAfterSuite` over `BeforeSuite/AfterSuite`
* Ensure that test-env ports are namespaced per ginkgo node so that there are no port clashes
* Amend the Makefile to run `ginkgo -p -randomizeAllSpecs -randomizeSuites` instead of `go test`

Alternatively to namespacing test-env ports, consider using a real long-living kind cluster that has all the controllers deployed over test-env and just run tests against it.

### Impact

Parallel tests execution should be faster. Also, randomising tests execution order would help for identifying flakes.

**Comment by georgethebeatle** [comment]
It looks like we are already running ginkgo [with parallelism](https://github.com/cloudfoundry/cf-k8s-controllers/blob/5a6938002aaa88aaf3c57bb7b4a223dca6c267fe/scripts/run-tests.sh#L31)

Do you think something is still missing @danail-branekov. If not, please close this chore.

**Comment by danail-branekov** [comment]
Yes, it seems so. However, we are running those tests with just 2 parallel nodes which is quite inefficient. Shall we have another chore to look at that, or we could use this one?

**Comment by georgethebeatle** [comment]
It's top of the backlog: [#302](https://github.com/cloudfoundry/cf-k8s-controllers/issues/302). Closing this one in favour of it.
