### ISSUE TITLE
[Explore]: What additional configuration do we need to support Pinniped (and other auth proxies) in "impersonation proxy" mode

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#856]
### Background

Some projects such as [Pinniped](https://pinniped.dev/) and [Jetstack OIDC Proxy](https://github.com/jetstack/kube-oidc-proxy) support external authentication providers on Kubernetes by acting as a proxy between clients and the Kubernetes API. These handle authentication in their own ways and then use [user impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) to make requests for the user.

The other day when we were experimenting with Pinniped we found that our current authentication strategy wasn't sufficient because of this.

The CF CLI authenticated with Pinniped just fine, but it received a client cert/key pair that was valid for Pinniped but not for the Kubernetes API. Since all of the user-scoped clients in our API Shim are built to hit the Kubernetes API directly, any calls they made were rejected with authentication errors.

### What to Explore
Figure out how to adapt the API Shim to be able to optionally point its user-scoped clients at something other than the K8s API. One option might be to add additional configuration (K8s API proxy address and CA cert?) to the shim that it can use when instantiating the user-scoped clients.

---

### Acceptance Criteria

At the end of this exploration we want to understand the following:

1. Is it possible to (optionally) configure the API Shim talk to support proxies like Pinniped
2. If so, document what you did in a comment on this issue and create a story to add this configuration for real

---

### Number of days this exploration is expected to take. This is what is “pointed”.

TBD

---

### Dev Notes

Pinniped works in two modes:

Using the K8s API Aggregation layer where K8s client requests go directly to the K8s API
In an "impersonation proxy" mode where K8s client requests go to Pinniped and then it takes actions on the user's behalf.
 
We can support mode 1 fine right now, but mode 2 has issues because the user-scoped clients we create in the API Shim are unaware of the fact that Pinniped exists and will instead send credentials meant for Pinniped to the Kubernetes API directly (where they will be rejected).

#### Resources
- https://pinniped.dev/docs/reference/supported-clusters/ (talks a little bit about the two Pinniped modes)
  - https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation 
- Where we create user-scoped clients: https://github.com/cloudfoundry/cf-k8s-controllers/blob/a1dd31293d3c0cd59bd3cd792f058ac693c95cd4/api/repositories/k8s_client.go#L26

**Comment by matt-royal** [comment]
To explore this, we set up a GCP environment with Pinniped by following [this tutorial](https://pinniped.dev/docs/tutorials/concierge-and-supervisor-demo/)

Once the environment was configured, we got the integration with Pinniped working end-to-end with some [horrible hacks in the code](https://github.com/cloudfoundry/cf-k8s-controllers/commit/eee37feca8fd297deb8f85dd171d741f75669d86#diff-dbbf781c8730222f6af11a8481f93399b3332deb43edca36865a02b64647afd1R65-R83) to re-direct the k8s client to the Pinniped proxy.

To get the Pinniped proxy IP and CA cert, you need to fetch the public IP address and CA cert for the Pinniped concierge entry point.

These can be pulled from the kubeconfig that the pinniped-cli (`pinniped get kubeconfig`) generates for you or you can fetch them from k8s directly:

{{k get secret -n pinniped-concierge pinniped-concierge-impersonation-proxy-ca-certificate -oyaml | yq -r .data[\"ca.crt\"] | base64 -d}}

{{k get service -n pinniped-concierge pinniped-concierge-impersonation-proxy-load-balancer -oyaml | yq -r .status.loadBalancer.ingress[0].ip}}

**Comment by matt-royal** [comment]
We wrote up https://github.com/cloudfoundry/cf-k8s-controllers/issues/956 as a follow-up to this story. /cc @tcdowney
