### ISSUE TITLE
[Chore]: Notify #cf-k8s-dev of CI failures on `main`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-k8s-controllers#871]
### Background

We have relaxed restrictions on how PRs can be merged in `main`: now PR branches don't need to be up-to-date with `main`. This will save us some time when trying to get a PR merged, but it makes it possible to introduce failures in `main` by mistake.

We run tests on each `main` commit, so we should be able to detect this issues promptly. We want to post failures to our Slack channel, so that they're visible.

### Impact

We'll be immediately aware of `main` being broken and we'll be able to fix it quickly.

### Dev Notes

* Here's the [official GitHub action](https://github.com/slackapi/slack-github-action) from Slack.
* The [`workflow_run`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) event should be what we need to trigger the message.

**Comment by georgethebeatle** [comment]
We have decided to switch main tests to concourse, which will solve notifications and will make history more easy to search and analyze. Closing.
