### ISSUE TITLE
Automatically set the appGUID label on CFApp records

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/cf-k8s-controllers#9]
We encode the relationships between resources in two ways: via "ref" fields under `spec` and via `metadata.labels`. Rather than rely on our code and/or kubectl users to always remember both, we want to require the spec field and automatically set the label via a MutatingAdmissionWebhook

## Blockers
- #4 

## Acceptance Criteria
```
GIVEN that I am targeting a k8s cluster
AND  that I have followed the README instructions to install the web hook
WHEN I apply the example CFApp resource in the repo (confirm ahead of time that it doesn't provide a GUID label)
THEN I should see it succeeds
WHEN I fetch the yaml for that record from the k8s API
THEN I should see that the GUID label has been set on the record and that it matches the `metadata.name` field
```

## Dev Notes
- We should be able to accomplish this via a MutatingAdmissionWebhook. The application that backs that hook should be the same that supports the ValidatingAdmissionWebhook from earlier issues (unless we have a good reason not to).
- This should apply to creation and updates of records. One alternative to explore: can we only handle creation and then make the label immutable?

**Comment by matt-royal** [comment]
The in-flight work for this is in the branch `issues/9`

**Comment by davewalter** [comment]
> One alternative to explore: can we only handle creation and then make the label immutable?

The `Default()` method does not know whether a resource is being created or updated, and there is no way to raise an error, so we chose to always set the `appGuid` label to the value of the `metadata.name` field. There does not appear to be a way to make a set of labels immutable.

**Comment by kieron-dev** [comment]
It seems likely that we'll need https://github.com/open-policy-agent/gatekeeper, or similar, to disallow changes to parts of some resources based on role.

If you find you need immutable labels, that should be simple enough to set up as an OPA rule.

**Comment by angelachin** [comment]
Yes, labels are not immutable and are not expected to be.

Should the sample resource have the label now deleted since the mutating webhook now creates it?

Otherwise everything looks good to me.

**Comment by akrishna90** [comment]
@angelachin Thats a good catch. Have addressed it in this [PR](https://github.com/cloudfoundry/cf-k8s-controllers/pull/33)

**Comment by angelachin** [comment]
Awesome, looks good to me. Seems like this issue can be closed out.
