### ISSUE TITLE
[Chore]: No need to check HNC readiness in install_dependencies.sh

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/cf-k8s-controllers#908]
### Background

HNC is [1.0.0](https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/tag/v1.0.0) now and they seem to have introduces liveness and readiness probes, which makes some [retries](https://github.com/cloudfoundry/cf-k8s-controllers/blob/052c3c4ac7ef44e37e5d27bb22f190bdf9834f66/scripts/install-dependencies.sh#L134-L142) in our install dependencies script redundant.

### Action to take

Remove the bits waiting for HNC to start responding

### Impact

Simpler scripts

**Comment by kieron-dev** [comment]
Picking this up as we need to bump dependency yaml to address dependabot's upgrade PR, and ignoring these start-up checks is trivial
